### ISSUE TITLE
Add open-discussions webhooks

### ISSUE THREAD

**Issue by abeglova** [mitodl/ocw-studio#1005]
When the site-pipeline and mass-publish-pipeline finish updating a course we should send a request to open-discussions to update search data

**Comment by pdpinch** [comment]
I saw this work on ocw-studio-rc / ocwnext-rc but it didn't seem to work on ocw-studio.odl.mit.edu / ocwnext.odl.mit.edu

Let me know if you need some specific details on what I changed to try it out.

**Comment by pdpinch** [comment]
@abeglova seems like this has been working for a long time now?
