### ISSUE TITLE
Show status of the page/resource/content

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-studio#1029]
As a course author, I'd like to see the status of a page/resource/content without opening/clicking it. So I can know whether a page/resource is `published` or `unpublished` OR it's `draft` or not.

`Draft` feature is introduced for pages, resources, and video gallery in [this ticket](https://github.com/mitodl/ocw-hugo-projects/pull/125).
When we have a list of pages/resources etc like shown below, we can not know whether it's draft or not, until we open it
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/93309234/154645781-7b945ff8-0f61-48b9-a17d-f9220b1bcd62.png">
So from a UX perspective, I guess it will be better to introduce a `status` label for each item of the list, which indicates whether the list item is draft or not.

we can also give a color to each label.
e.g:
- `Published` label can have a greenish color
- `Draft/unpublished` label can have a yellowish/orange color.
But the designer will be a better person to decide this

#### Designs and Mockups
- not having any for now.

#### Acceptance Criteria:

- [ ] `status` label is shown for all the items of pages, resources and video gallery list indicating whether each item is draft or not

**Comment by alicewriteswrongs** [comment]
we should re-use the UI we already have for sites:

![Screen Shot 2022-02-23 at 12 58 11 PM](https://user-images.githubusercontent.com/6207644/155378781-4d443431-19ee-499d-90e3-c1233544932a.png)

I think we need three states:

- 'Draft': the content has `draft: true`
- 'Unpublished': the content has `draft: false` but has not yet been published
- 'Published': the content has `draft: false` and has been previously published

**Comment by MAbdurrehman12** [comment]
@pdpinch Do you think this is something we should work on? if yes, then what can be its priority?

**Comment by pdpinch** [comment]
We made a first pass at this. There is a new issue for more changes: https://github.com/mitodl/hq/issues/6017
