### ISSUE TITLE
Link to course collections

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1038]
As a course author, I should be able to add links to course collections in pages.

#### Designs and Mockups
Horizontal space is a bit limited in our tabs. This might be a good approach for course collections + resource collections, but focus should be on course collections for this feature.

<img width="550" alt="Screen Shot 2022-02-18 at 5 16 12 PM" src="https://user-images.githubusercontent.com/9010790/154774440-a172d704-006c-4de5-b9ba-27b35ae1bbef.png">

#### Acceptance Criteria:

In CKEditor on a course page:
- [ ] Clicking "Add link" should open link-picking dialog with a "Collections"
- [ ] Clicking "Collections" tab should populate dialog with filterable list of **course collections**
- [ ] it should be clear that the list is course collections for now, and not resource collections 

#### Out of Scope

- Adding resource collections

**Comment by Ferdi** [comment]
I'd keep it simple for now - just a "Collection" tab that shows all collections.   We might want to redesign this a bit anyway , the tabs is not scaling.
