### ISSUE TITLE
Multiple git commits for one small change

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1040]
### Steps to Reproduce

1. I made a small change to the ocw-www site on RC, resulting in this commit in the main branch https://github.mit.edu/ocw-content-rc/ocw-www/commit/dfffdf08a61f89362b2251a63fe8f860052ed1ff
2. Publishing to the staging server, resulted in 8 additional, empty commits to the main branch, starting with https://github.mit.edu/ocw-content-rc/ocw-www/commit/94911d020189310d713f7e3b09045dec7e8df243 and ending with https://github.mit.edu/ocw-content-rc/ocw-www/commit/4233cbdd8a4333dcf49e82927671f0b7ec75115f
3. There was one additional, merge commit on the preview branch: https://github.mit.edu/ocw-content-rc/ocw-www/commit/9d53b62a88bd73470c5a7e0762aeac684be16033

### Expected Behavior

I think only one commit is necessary, to the main branch, followed by one merge commit to the preview branch

### Actual Behavior

9 commits? And why are the authors @mbertrand and @gumaerc ?

**Comment by mbertrand** [comment]
There were 7 resources with outdated checksums.  The function to calculate checksums was last modified in June, it could be that checksums weren't mass updated afterward, and I'm guessing that these resources were created before then and so have outdated checksums.  Consequently, studio thinks they have been modified (they don't match the `synced_checksum` value from the previous git commit) and try committing them again.

When merging, commits are grouped by user.  If changes are made (or seemed to be made in this case) by 3 users, there will be 3 commits.

**Comment by pdpinch** [comment]
So you think this is a one-time event?

**Comment by mbertrand** [comment]
It would keep happening until the checksums are fixed either through a shell or updating the affected files via the UI.  But it looks like someone else already did that since yesterday when I first checked them.  This morning they are synced.

**Comment by mbertrand** [comment]
Turns out that the new management command for fixing markdown does a bulk update, which bypasses the django signal used to update the content syncstate checksums (used to determine what should be committed to git).  I will work on updating that command to update both the content and the sync state checksums.
