### ISSUE TITLE
Data migration: root relative links are broken

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1042]
This is similar to #1041 and perhaps could be corrected the same time.

### Steps to Reproduce

Most of the "slides" links in RES.6-012 are broken. I think they were hardcoded in Plone to root-relative URLs. Can we migrate them to resource links?

legacy: https://ocwnext.odl.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/pages/part-i-the-fundamentals/
markdown: https://github.mit.edu/mitocwcontent/res.6-012-spring-2018/blame/main/content/pages/part-i-the-fundamentals.md#L71-L73
nextgen: https://ocwnext.odl.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/pages/part-i-the-fundamentals/

**Comment by pdpinch** [comment]
Another example: https://ocwnext.odl.mit.edu/courses/res-18-006-calculus-revisited-single-variable-calculus-fall-2010/pages/study-materials/

**Comment by pdpinch** [comment]
@ChristopherChudzicki do you think this can be closed now?

**Comment by ChristopherChudzicki** [comment]
Closing this in favor of #1233
