### ISSUE TITLE
During QA, some authors are linking to courses using the ocwnext.odl.mit.edu base url

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-studio#1054]
### Steps to Reproduce

Some authors need to link to other OCW courses and some authors are linking to courses by copying the URL from the NextGen site (ocwnext.odl.mit.edu) and pasting into the standard "Link" tool in the CK editor. You can see an example of this in  18.100c on the [https://ocw-studio.odl.mit.edu/sites/18-100c-real-analysis-fall-2012/type/page/](Syllabus Page). Scroll down to the three "prerequisite links" and see screenshot below.

After a brief conversation with @pdpinch, we thought this could be something we repair after the QA process, because we don't have a better suggestion at the moment.

### Related Issues
Studio should probably author a way to link to courses through the "add link" mechanism (like we do for pages, collections, etc). 

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/1703442/155380494-82c97d35-1f68-4134-8c13-b95cab4dadb2.png)

**Comment by pdpinch** [comment]
@ChristopherChudzicki did a find and replace to update all these.
