### ISSUE TITLE
create and edit sub/superscript text in studio

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1061]
As a course author, I need to be able to add subscript and superscript text in the wysiwyg editor, for math and chemistry courses. 

#### Designs and Mockups

TBD

#### Acceptance Criteria:

- [ ] write a proposal for how to approach this problem, in studio, in markdown and in hugo
- [ ] Add subscript or superscript text 
- [ ] publish subscript and superscript text

#### Out of Scope

- editing would be nice, but if its difficult we can instruct authors to delete and re-add the sub/superscript when they need to

**Comment by Wassaf-Shahzad** [comment]
### Proposal for Approach
@pdpinch 
The approach I went with as shown in this PR https://github.com/mitodl/ocw-studio/pull/1469 was to create a Markdown Syntax Plugin to translate subscripts and superscripts into Markdown and vice versa. As @ChristopherChudzicki pointed out this approach does have a short coming which is nested shortcodes. In testing out subscript in resource_link, I have discovered that no formatting works in resource_links

**Comment by Wassaf-Shahzad** [comment]
> > In testing out subscript in resource_link, I have discovered that no formatting works in resource_links
> > Two things I want to add:
> 
> * I believe that italics and bold inside resource_links (or wrapping the entire link) do work in Hugo if put manually into the markdown, Studio just seems not to be handling it correctly.
>   In contrast, any formatting that is shortcode-based (which italics and bold aren't) would not work in Hugo because shortcodes inside shortcode parameters is not supported.
> * Superscripts/subscripts inside resource link titles may be a reasonably important use-case, e.g., links to scientific articles with chemical formulas in the article title. (A lot of the nested shortcodes we encountered in migrated data were chemical formulas or math in resource link titles.)
> 
> IMO, when it comes to math and chemical formulas, MathJax (or some other web LaTeX implementation, like [KaTeX](https://github.com/KaTeX/KaTeX))

@ChristopherChudzicki, Sorry for not explaining it correctly but yes I was talking in terms of studio and not Hugo

**Comment by ChristopherChudzicki** [comment]
After a conversation with @pdpinch today I did a brief exploration. With Hugo 0.101

resource_link.html
```
{{- $uuid := index .Params 0 -}}
{{- $title := index .Params 1 -}}
{{- $anchor_id := index .Params 2 | default ""}}
{{- range where $.Site.Pages "Params.uid" $uuid -}}
<a href="{{ .Permalink }}">
    {{ $title | $.Page.RenderString  }}
</a>
{{- end -}}
```

Markdown:
```md
Hello

This is a {{< resource_link "1c082150-35bb-4236-af04-c67f3976fd42" "resource link with **bold** and super{{< sup \"scripts with spaces\" >}} " >}}

World
```

Screenshot:
<img width="663" alt="Screen Shot 2022-09-29 at 3 47 05 PM" src="https://user-images.githubusercontent.com/9010790/193145003-a1978d3a-71d1-4d58-a334-8dea7bd5a8a4.png">

Notes:
- I thought this was going to work better with hugo's opening + closing shortcodes, but the superscripts were getting commented out as "raw HTML" by hugo. Possibly related: https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted
- Note that the superscript shortcode inside the resource link has its quotes escaped: `{{< sup \"scripts with spaces\" >}}` ... I was surprised that worked...but it did.

@gumaerc Does the above seem like a reasonable approach?

**Comment by gumaerc** [comment]
@ChristopherChudzicki This seems to be a fine approach. FYI, accourding to https://www.docsy.dev/docs/adding-content/shortcodes/:

"Using the bracket styled shortcode delimiter, `>}}`, tells Hugo that the inner content is HTML/plain text and needs no further processing. Changing the delimiter to `%}}` means Hugo will treat the content as Markdown. You can use both styles in your pages."

So, In your notes when you mentioned that your superscripts were getting stripped as "raw HTML," was the wrapping shortcode delimited with the angle brackets or percent signs? Either way, I put up a PR here in `ol-infrastructure` to upgrade the version of Hugo we use in Concourse builds. I upped the version number so once this merges we can test by upping the version number in the pipeline definition and then commit that change if everything works properly.

**Comment by ChristopherChudzicki** [comment]
## Status Update

We moved forward this feature by allowing a specific whitelist of HTML tags to be used in OCW markdown, currently just `["sub", "sup"]`.  See https://github.com/mitodl/ocw-studio/pull/1588 for more details.

After releasing to RC, we discovered the following issue:

https://user-images.githubusercontent.com/9010790/205384591-0ab103a2-0a4c-4691-96b1-c1bbde7eb649.mov

Notably:
- This only happens when adding a **new** script AND clicking **immediately** after the link.
- This **might** be a CKEditor issue... I removed all custom plugins (i.e., input is HTML output is HTML, no resource links, etc) and the error still occurs locally. This needs more investigation. _There are similar issues on the CKEditor repo, and this may have been fixed in new versions of CKEditor. Here's one: https://github.com/ckeditor/ckeditor5/issues/7697_
- I am confused when the error manifests itself as
    - console.error locally
    - fatal crash of editor on RC

I am vacation for the next week, and will pick this up upon return.

**Comment by ChristopherChudzicki** [comment]
I tested the CKEditor plugins in a bit more isolation at https://github.com/ChristopherChudzicki/ck-test.

Using CKEditor 35 seems to fix this issue:
- branch [ck-31](https://github.com/ChristopherChudzicki/ck-test/tree/ck-31) uses CKEditor v31 (same as current ocw-studio). Then (1) add a link, (2) add superscript within link, (3) click directly after link shows console errors, just like video above.
- branch [ck-35](https://github.com/ChristopherChudzicki/ck-test/tree/ck-35) uses CKEditor v35; the error seems not to occur

**Comment by ChristopherChudzicki** [comment]
✅ 😌
