### ISSUE TITLE
searching for site `21M.380` doesn't return any results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1069]
### Steps to Reproduce

1. Visit https://ocw-studio-rc.odl.mit.edu/sites/?q=Music+and+Technology%3A+Sound+Design
2. you should get one result, https://ocw-studio-rc.odl.mit.edu/sites/21m-380-music-and-technology-sound-design-spring-2016/
3. Visit https://ocw-studio-rc.odl.mit.edu/sites/?q=21M.380

### Expected Behavior

- should get the same one result, https://ocw-studio-rc.odl.mit.edu/sites/21m-380-music-and-technology-sound-design-spring-2016/ 

### Actual Behavior

- no results

**Comment by mbertrand** [comment]
Reopening this because certain course numbers still don't show up in search results.  Example: anything starting with "HST", like "HST.582J"
