### ISSUE TITLE
Add missing content for legacy courses without importing

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#1070]
Related to https://github.com/mitodl/ocw-data-parser/issues/169, https://github.com/mitodl/ocw-to-hugo/issues/459, https://github.com/mitodl/ocw-to-hugo/issues/478

https://github.com/mitodl/ocw-data-parser/issues/169: Sync from S3 bucket `open-learning-course-data-<env>` to the ocw-studio bucket (Tobias has a script for this) - after another ocw-import command is run in open-discussions with the latest ocw-data-parser version.

https://github.com/mitodl/ocw-to-hugo/issues/459: Add new WebsiteContent objects for the new video resource markdown files generated by ocw-to-hugo 

https://github.com/mitodl/ocw-to-hugo/issues/478: Modify `video_thumbnail_file` value in markdown for affected videos.

**Comment by ChristopherChudzicki** [comment]
Related to #1042, too. A lot of the root-relative links are to these files.

**Comment by mbertrand** [comment]
I was going to wait until they are republished, but the missing resources (the ones that I know of anyway) have been imported into production studio.

**Comment by pdpinch** [comment]
I think these were published on Friday?
