### ISSUE TITLE
can't update instructor salutation

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1073]
### Steps to Reproduce

1. Update an instructor missing a salutation, e.g. https://ocw-studio-rc.odl.mit.edu/sites/ocw-www/type/instructor/?q=mattuck
2. Set the salutation to "Prof"
3. Save the instructor
4. Publish the site to stage. 
5. Publish the site to production. 
6. Confirm the update is in github, at https://github.mit.edu/ocw-content-rc/ocw-www/blob/release/content/instructors/583cc582-1f48-236c-af5a-b2f4750fef40.md
7. Confirm the instructor is published on the web site, at https://ocwnext-rc.odl.mit.edu/instructors/583cc582-1f48-236c-af5a-b2f4750fef40/index.json
8. In a different course, such as https://ocw-studio-rc.odl.mit.edu/sites/peters-test-2021-09-29-1/type/metadata/ and open the metadata section
9. Add the instructor you edited. 

### Expected Behavior

Salutation should be part of the instructor's title when added. 

### Actual Behavior

Still no salutation. 

### Screenshot or Screencast

<img width="722" alt="image" src="https://user-images.githubusercontent.com/430126/156102600-d55e7193-26ce-4da2-bdba-aed982b6ba30.png">

**Comment by MAbdurrehman12** [comment]
@alicewriteswrongs I agree with what you stated and I think we can go with this approach
> One approach is to basically change .title to a computed property by programmatically setting in on instructor objects when they're saved

but with hiding the `title` field from course author, so course author will only see the metadata while saving/updating an instructor, and in the backend we can programmatically set the title to `Salutation + first_name + middle ...` so this title field becomes a ready-to-go field. As I also noticed that title is being used as an instructor's full name in a few other places as well.

What do you think?

**Comment by alicewriteswrongs** [comment]
Yeah I think that makes sense to me, especially if we make it so the user can't edit the field, since if they edit it and then it gets overwritten that could be confusing.

**Comment by pdpinch** [comment]
Turns out this is user error. We can improve that data model and/or the UX, but it’s not a release blocker. I’m putting it on hold.
