### ISSUE TITLE
Course pages not available to edit in Studio; RES-2.002

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-studio#1080]
### Steps to Reproduce
Supplementary Resource: [Studio RES-2.002](https://ocwnext.odl.mit.edu/courses/res-2-002-finite-element-procedures-for-solids-and-structures-spring-2010/video_galleries/linear/) 
This supplementary resource has 2 pages on the [NextGen Site](https://ocwnext.odl.mit.edu/courses/res-2-002-finite-element-procedures-for-solids-and-structures-spring-2010/video_galleries/linear/). In Studio, there are zero pages listed.

### Expected Behavior
We should see two editable pages.

### Actual Behavior
Zero pages are listed.

### Stacktrace
N/A

### Related Issues
N/A

### Screenshot or Screencast
Studio screenshot showing zero editable pages.
![image](https://user-images.githubusercontent.com/1703442/156583321-7f89e5f9-fe82-4835-9f15-be052a345c44.png)

NextGen Site where we see two pages: 1) Linear Analysis, 2) Nonlinear Analysis
![image](https://user-images.githubusercontent.com/1703442/156583536-f9ed8a2a-adb6-4e12-b969-0182f43a1f84.png)

**Comment by MAbdurrehman12** [comment]
I think the pages which you're seeing are from video gallery section: 
Studio:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/93309234/157029457-6b87d9f5-b1fc-4752-bc60-0d5cfd08e8fa.png">
`video gallery` in nextgen URL: 
<img width="933" alt="Screenshot 2022-03-07 at 4 57 34 PM" src="https://user-images.githubusercontent.com/93309234/157030323-a3ffa2c1-d318-42e3-99b9-821af9653bff.png">

**Comment by dseaton** [comment]
Those video galleries have blank content in the editing window. So either these need to be pages, or the content needs to be migrated to the description fields for each gallery.

![image](https://user-images.githubusercontent.com/1703442/157051077-1903c62c-d095-47c6-a045-8eb6a9b9792a.png)

**Comment by dseaton** [comment]
I am not sure about overall scope, but it seems that supp resources where video galleries are linked from the left nav, the authors cannot edit the page content related to those galleries.

Another example: [RES-9-003](https://ocw-studio.odl.mit.edu/sites/res-2-002-finite-element-procedures-for-solids-and-structures-spring-2010/type/video_gallery/edit/4f0f5719-a469-9634-caf5-43161dea55c0/)

**Comment by ChristopherChudzicki** [comment]
This should be resolved with https://github.com/mitodl/ocw-hugo-projects/pull/137
