### ISSUE TITLE
CKEditor underline functionality doesn't work

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1084]
### Steps to Reproduce

 - Create any kind of content in your site that has a markdown section
 - In the markdown editor, highlight some text and click underline
 - You should see the text underlined
 - Click save and then re-open the content for editing

### Expected Behavior

When re-opening the content it should be underlined in CKEditor

### Actual Behavior

The underline is not saved

### Additional notes

This issue likely has to do with the fact that markdown does not have a standard representation for underlined text.  Likely, we will have to create a shortcode in `ocw-hugo-themes` to support underline.

**Comment by pdpinch** [comment]
Can this be closed?

Does this affect an actual known course? I'm not sure why we needed this.

**Comment by ChristopherChudzicki** [comment]
Closing in favor of https://github.com/mitodl/ocw-studio/issues/1470
