### ISSUE TITLE
bug: mass publishes can lead to unexpected behavior

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#1111]
During a conversation today we surfaced a new issue with the content authoring -> publishing timeline in ocw-studio that will lead, as it is presently implemented, to surprising behavior for OCW course authors.

The issue can be summarized quickly as follows: mass publishes currently publish _all content on ocw-studio_ which isn't marked as `draft`, including content which has _never_ been intentionally published to production. 

### background

**Mass publishes** are publishes of all the content on ocw-studio. They happen in a few scenarios, and may be triggered manually using a management command or, importantly, they are triggered automatically when there is a new version of the theme released (in order for the theme updates to be reflected on all courses we need to republish them all).

We currently have a **draft** status which can be set on individual *pieces of content*. This will allow that content to be published to the 'Staging' environment but it will _not_ be published to 'Production'.

Although we support this publishing opt-out for individual pieces of content, we have no such mechanism for a whole website.

### problem scenario

The problem will emerge under the following conditions:

1. course authoring team creates a new course (`example-course`) and starts developing content for it, possibly publishing it to 'Staging' in order to test rendering and so on.
2. a change to the theme is merged to `ocw-hugo-themes` and released, triggering a mass publish
3. although `example-course` has never been published to production before, the mass publish pipeline will pick it up and publish it to production.

So there is an issue here where the OCW course authoring team expects to have a workflow supported where they iterate on a course as a group for some amount of time, publishing to staging to share an in-progress form for feedback, without it being published to production. However, our current setup w/ releasing theme changes creates a scenario under which their in-progress work may be silently and unexpectedly released to production before it is ready.

### proposed fix

In order to address this issue we should make publishing to production _explicitly opt-in_.

We can accomplish this by excluding courses from the mass publish pipeline if they have never been manually published to production before.

We should:

- add documentation / helptext that explains that until a course is manually published it will not be released to production, even if it is published to staging
- modify the mass publish pipeline to only publish courses which have been previously published. we are already using the `publish_date` property on the website model to determine when a site has been published[^1], so we can use that in order to filter here too.

[^1]: See  #887, #916, #924, #904 for discussion on this and relevant implementation.

**Comment by Ferdi** [comment]
could we add a flag at the course level "Publish = true/false"

**Comment by alicewriteswrongs** [comment]
Definitely, that would be another way to signal explicitly that a course should be published to prod or ignored by the mass publish.

I'm sort of inclined towards using 'has this been manually published?' as the signal for this because the content authors are familiar with that as a mechanism and it seems intuitive to me that if I haven't explicitly 'promoted' something to production by clicking a big 'publish to production' button, then it shouldn't show up there yet. It's also in line with the way that we currently determine whether courses have been previously published, for purposes of allowing or disallowing linking to content within those courses.

This also raises the question of what should happen if a course has been published to prod previously and then we want to un-publish it - should we support such an action, how would it be implemented, etc.

**Comment by mbertrand** [comment]
The mass-publish concourse pipeline gets the list of sites to be published from a view that should be excluding any sites created in Studio where `live_publish_status=None` - it will publish all legacy imported sites.
https://github.com/mitodl/ocw-studio/blob/master/websites/views.py#L239-L245

**Comment by alicewriteswrongs** [comment]
oh that's good news! We were discussing how this works this morning and I think none of us were aware (or forgot that). I'll go ahead and close this then.
