### ISSUE TITLE
Quick quiz questions contain raw HTML, do not render

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1119]
### Steps to Reproduce
1. Compare
    - legacy ocw: https://ocw.mit.edu/courses/sloan-school-of-management/15-071-the-analytics-edge-spring-2017/integer-optimization/eharmony-maximizing-the-probability-of-love/quick-question-711/
    - ocwnext: https://ocwnext.odl.mit.edu/courses/15-071-the-analytics-edge-spring-2017/pages/integer-optimization/eharmony-maximizing-the-probability-of-love/quick-question-711/
2. Inspect the markdown at https://github.mit.edu/raw/mitocwcontent/15.071-spring-2017/main/content/pages/integer-optimization/eharmony-maximizing-the-probability-of-love/quick-question-711.md?token=AAAFZYXG5UJGGZXTWWCPTF3CHCEMC ... lots of raw HTML

### Actual Behavior
Page does not render at all in ocw next and contains raw HTML, not markdown.

### Expected Behavior

Unsure.

### Other Notes
I believe this is limited to the following courses
```
course                                                                  number of such pages
--------------------------------------------------------------------------------------------
6-042j-mathematics-for-computer-science-spring-2015	                107
15-071-the-analytics-edge-spring-2017	                                58
16-90-computational-methods-in-aerospace-engineering-spring-2014	5
14-01sc-principles-of-microeconomics-fall-2011	                        3
18-05-introduction-to-probability-and-statistics-spring-2014       	1
````

**Comment by ChristopherChudzicki** [comment]
@dseaton Came across this while looking into `resolveuid` links in markdown. This might well be on your radar already... I believe I've heard these quiz questions have been problematic elsewhere.

**Comment by pdpinch** [comment]
The courses in question were unpublished (or should have been; 15.071 keeps cropping back up)
