### ISSUE TITLE
Broken links in video related resource tab

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1141]
### Steps to Reproduce

legacy: https://ocw.mit.edu/resources/res-6-010-electronic-feedback-systems-spring-2013/course-videos/lecture-1-introduction-and-basic-concepts/
nextgen: https://ocwnext.odl.mit.edu/courses/res-6-010-electronic-feedback-systems-spring-2013/resources/lecture-1-introduction-and-basic-concepts/
github: https://github.mit.edu/mitocwcontent/res.6-010-spring-2013/blame/main/content/resources/lecture-1-introduction-and-basic-concepts.md#L12

1. On nextgen, expand the relates resource section below the video
2. Click on the Lecture Notes links

### Expected Behavior

- The PDF link should be root-relative, and link to `/courses/res-6-010-electronic-feedback-systems-spring-2013/resources/mitres_6-010s13_lec01/`

### Actual Behavior

The PDF link is root-relative, but it has extraneous directories: `/courses/res-6-010-electronic-feedback-systems-spring-2013/resources/lecture-1-introduction-and-basic-concepts/resources/mitres_6-010s13_lec01`

**Comment by ChristopherChudzicki** [comment]
Closing this. Those links were fixed.. Just needed to be published.
