### ISSUE TITLE
Fix file urls whose legacy filenames were not unique

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1145]
_This issue affects ~500 file urls (including images)_
### Steps to Reproduce
1. Visit https://ocwnext.odl.mit.edu/courses/mas-962-special-topics-new-textiles-spring-2010/pages/assignments-and-projects/nonwoven/assignment-5-posable-surface/#process

### Expected Behavior
Image should load

### Actual Behavior
Image does not load

### Notes
Urls to files with non-unique legacy filenames are still broken. The page above is an exampe. The legacy could had two images called "process.jpg" with different parent content:
```
/courses/media-arts-and-sciences/mas-962-special-topics-new-textiles-spring-2010/assignments-and-projects/final-project
    .../final-project-sneaky-slippers/process.jpg
/courses/media-arts-and-sciences/mas-962-special-topics-new-textiles-spring-2010/assignments-and-projects/nonwoven
    .../assignment-5-posable-surface/process.jpg
```

The parentage information was not originally migrated, so these links could not be fixed as part of #1086

### Blocks:
- [x] migrate the parentage information in ocw-to-hugo
- [ ] backpopulate the parentage information https://github.com/mitodl/ocw-studio/pull/1115

@ChristopherChudzicki needs to Fix that PR ☝️  then this will be unblocked.

**Comment by pdpinch** [comment]
Can this be closed now?

**Comment by ChristopherChudzicki** [comment]
@pdpinch Yep, closing!
