### ISSUE TITLE
first pass of styling for the site

### ISSUE THREAD

**Issue by aliceriot** [mitodl/ocw-studio#115]
We want to get some styling in place so the site looks a little less 'placeholder-ey.'

We should strive to keep our CSS minimal and consistent. Every project we have has had many redesigns which always end up being applied inconsistently, we end up with many buttons, etc. Let's not do that here!

**Comment by noisecapella** [comment]
Are you working off of these mockups? https://xd.adobe.com/view/6074f9dd-fa3f-4a6c-a1fe-4d70e7d0ca78-3527/

**Comment by aliceriot** [comment]
yes
