### ISSUE TITLE
Add a link to a video gallery 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1152]
As a course author, I'd like to be able to link to a video gallery, but they don't show up in the "Add Link" widget. 

#### Designs and Mockups

If possible. include video galleries on the "pages" tab in the add a link widget. 

#### Acceptance Criteria:

- [ ] Allow user to add a link to a video gallery
- [ ] export a working resource_link short code to github

**Comment by pdpinch** [comment]
@Wassaf-Shahzad this looks like it's done to me, is it?

**Comment by Wassaf-Shahzad** [comment]
This issue had been closed
