### ISSUE TITLE
Embed resource thumbnails not showing up in production studio

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1153]
**Note:** Images seem to show up fine in the published site.

### Steps to Reproduce

1. Visit https://ocw-studio.odl.mit.edu/sites/18-152-introduction-to-partial-differential-equations-fall-2005/type/page/edit/4d482928-9d2b-235f-6034-cc905080fc70/

### Expected Behavior

Images should show up in markdown body

### Actual Behavior

Image not found icon shows with a src like:

```
https://ol-ocw-studio-app-production.s3.amazonaws.com/courses/18-152-introduction-to-partial-differential-equations-fall-2005/9a384be87fefb7342f3f191afec2c6a1_R1.jpg
```

### Screenshot or Screencast

<img width="1389" alt="Screen Shot 2022-03-22 at 12 55 58 PM" src="https://user-images.githubusercontent.com/9010790/159533800-61d2111a-9282-45b1-82ae-45752a3e636c.png">

**Comment by pdpinch** [comment]
@blarghmatey I think this can be closed now?
