### ISSUE TITLE
disable mass import

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1167]
Now that we have users in ocw-studio working on legacy content, it's not safe to run imports unfiltered. 

We should remove the code, to avoid any possibility of user error.

**Comment by gumaerc** [comment]
So there are 2 management commands that can mass-import `ocw-to-hugo` data; `import_ocw_course_sites` which imports full courses and `overwrite_ocw_course_content` which overwrites single metadata properties in front matter.  I think for the time being, we will still need the latter, but with the former we could make `--filter` a required argument.  This would still allow someone to do something like `./manage.py import_ocw_course_sites -b ocw-to-hugo-output-production --filter 18-` and import an entire department though.  If we wanted to be more strict about it, we could change that to specify a course or list of courses like `mass_publish`, or we could just remove the command altogether.  I think we should keep it around for importing 1-off courses though, so I think making filter a required field and standardizing it to the way we filter on courses with our other commands would be the best approach.  What do you think @pdpinch ?

**Comment by pdpinch** [comment]
In general, standardizing is good. 

In this particular case, what I had in mind was requiring the filter parameter. Does it have a minimum number of characters (perhaps 2)?
