### ISSUE TITLE
can't save course collection without a featured course collection

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1175]
### Steps to Reproduce

1. go to https://ocw-studio.odl.mit.edu/sites/ocw-www/type/course-collection/edit/6c1cc52b-3c3d-4a6d-a73c-2fe319b435f7/
2. make a trivial change to the collection description, like adding a space
3. Click save

### Expected Behavior

- collection saves
- drawer closes

### Actual Behavior

- nothing happens
- no error message

**Comment by pdpinch** [comment]
This bug seems to only exist on prod, not RC. 

Two things to check:
- are Prod and RC using the same, up-to-date starter configuration?
- Is there an issue with the course list data on prod? It was migrated from an earlier data structure

**Comment by mbertrand** [comment]
This should be fixed now.
