### ISSUE TITLE
No error message when user's session has expired

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1177]
### Steps to Reproduce

Not sure if this will work, but it's happened enough times that I'm confident there is a problem. 

1. Log into ocw-studio and 
2. Delete the session cookie
3. Click a button 

### Expected Behavior

Either: 
- user gets an error message instructing them to log in again
- OR, user is logged in again automatically with social auth 

### Actual Behavior

- the UI fails silently

**Comment by ChristopherChudzicki** [comment]
This is the current redirect prompt, which triggers on all API responses that reject with an authentication error (not other errors, like permission errors).

<img width="1462" alt="Screen Shot 2022-05-05 at 11 45 33 AM" src="https://user-images.githubusercontent.com/9010790/166961676-97e91e16-653e-42ae-a689-39deb520f9ad.png">

**Comment by ChristopherChudzicki** [comment]
@pdpinch @Ferdi This has been released.
