### ISSUE TITLE
Setting a published page to draft should remove it from the production site

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1189]
### Steps to Reproduce

1. Create a page
2. Publish it to staging and production. Confirm that it was published in both sites.
3. Set Draft=True in the page's metadata
4. Publish is to staging and production 

### Expected Behavior

- the page with draft=true should still be available on the stage/preview site
- the page with draft=true should be removed from the production site

### Actual Behavior

- the page with draft=true is still available on the stage/preview site
- the page with draft=true _is still available_ on the production site

### Related Issues

- [ ] #1190

**Comment by Wassaf-Shahzad** [comment]
@pdpinch So by removing the page from production site, You mean to remove it from the live repo as well ?
Hopefully I am understanding this correctly.

**Comment by Wassaf-Shahzad** [comment]
@pdpinch @gumaerc Following is a detailed analysis of my RnD

## Current Implementation

The current implementation uses the `sync_all_content_to_backend` called form the publish_website function to upload content to GitHub. The content is filtered based on checksum which informs us whether a particular content of a website has been updated. All of this takes place in the function `upsert_content_files_for_user` in the file content_sync > apis > github.py, line 326.

We could change the queryset to filter out pages which are draft in the case of a live version but this will only accomplish the following
- Stop the creation of draft pages in live site.
- Stop updating of live pages which were updated to draft from live.

To remove draft pages from live site, we need to delete them from the github repo.

## Recommended Solution

We can create a new delete_content pipeline, which could be used to remove content based on certain parameters. Using this new concourse pipeline, we could filter out draft pages on live and remove them. This could be done before publishing insuring no draft pages are published on live.

**Comment by pdpinch** [comment]
We discussed and pursuing the `--delete` option seems like the way forward. I'm assigning this issue to Carey.
