### ISSUE TITLE
Setting a published page to draft should remove it from the production search index

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1190]
### Steps to Reproduce

1. Create a page
2. Publish is to staging and production. Confirm that it was published in both sites and the page appears in the resource search
3. Set Draft=True in the page's metadata
4. Publish is to staging and production 

### Expected Behavior

- the page with draft=true should be removed from the resource search index 
- pages and resources should behave the same way 

### Actual Behavior

- the page with draft=true _is still available_ in the resource search index 

For example: https://ocwnext.odl.mit.edu/search/?q=Visualizations%20RealOne%E2%84%A2%20Player&t=Physics&t=Electromagnetism&type=resourcefile still returns the [Visualizations page](https://ocwnext.odl.mit.edu/courses/8-02t-electricity-and-magnetism-spring-2005/pages/visualizations/) even though it has been marked as draft in [studio](https://ocw-studio.odl.mit.edu/sites/8-02t-electricity-and-magnetism-spring-2005/type/page/edit/3e9d053a-11ee-effa-00de-c3b42819928c/)

### Related Issues

- [ ] #1190

**Comment by pdpinch** [comment]
@gumaerc do you think this can be closed since we added `--delete` to the sync?

**Comment by gumaerc** [comment]
@pdpinch I just tested this and yes, the change to the single course pipeline that runs the sync with `--delete` accomplishes this.
