### ISSUE TITLE
Fix flaky frontend test

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1207]
Twice recently I've had frontend tests fail on CI in a PR that did not touch frontend at all. For example, https://github.com/mitodl/ocw-studio/runs/5854057454?check_suite_focus=true

Acceptance Criteria:
- [ ] Figure out why and fix it.

**Comment by pt2302** [comment]
Another possible example: https://github.com/mitodl/ocw-studio/runs/7197287993?check_suite_focus=true

**Comment by pt2302** [comment]
Possibly related: https://github.com/mitodl/ocw-studio/issues/269.

**Comment by pt2302** [comment]
Another example: https://github.com/mitodl/ocw-studio/runs/7362418653?check_suite_focus=true

**Comment by pdpinch** [comment]
any update on this @Wassaf-Shahzad ?

**Comment by Wassaf-Shahzad** [comment]
Sorry no @pdpinch I could not reproduce this locally

**Comment by HussainTaj-arbisoft** [comment]
To determine this issue's impact and existence, I ran the `SingletonsContentListing.test` multiple times. (Thanks to https://github.com/mitodl/ocw-studio/issues/1207#issuecomment-1185785648, I did not have to run the entire suite).

| Test | Count |
| ------- | ----- |
| Passed | 159 |
| Failed | 4 |
| Total | 163 |

Although it could use more runs for a more accurate number, we can say this issue **impacts 2.4% of the PRs**.

I ran a few experiments but unfortunately, I could not determine the cause of the problem yet.

Here's a sample of the error message
```
  ● SingletonsContentListing › loads content detail from the API if needed without content context

    AssertError: expected stub to not have been called but was called once
        stub('/api/websites/suscipit-autem-enim-sapiente-qui/content/eos/', 'GET', { body: undefined, headers: undefined, credentials: undefined }) => {
      body: {
        text_id: 'ec6675ae-91bd-4bdd-b7a2-1579864907ce',
        title: 'Quia facere veritatis',
        type: 'molestiae',
        updated_on: '2006-03-25T18:23:21.117Z',
        markdown: 'Quasi alias minima harum voluptatem dolor aut odit corporis. Consequatur magni aut officia quis quia. Doloribus est non quo quibusdam in ab cumque sed. Amet enim perspiciatis. Voluptas earum temporibus voluptates animi dolorum.',
        metadata: { description: 'Eum quidem architecto accusantium.' },
        content_context: [],
        url_path: 'At et consequatur eaque iure. Occaecati saepe doloremque repellendus facere quo molestiae quos amet. Occaecati cumque dolorem. Ipsa et aperiam voluptatem quia consequuntur impedit tempore quis voluptas. Minima reiciendis adipisci eaque animi cumque. Quis fuga tempora hic cumque voluptas asperiores.'
      },
      status: 200
    } at Object.execute (/src/static/js/util/integration_test_helper_old.tsx:65:31)

      170 |       // API should not initially be called since we already have the first item in our websiteContentDetails
      171 |       // entities state
    > 172 |       sinon.assert.notCalled(contentDetailStub)
          |                    ^
      173 |       const tabLink = wrapper.find("NavLink").at(tabIndexToSelect)
      174 |       act(() => {
      175 |         // @ts-expect-error Not mocking whole event

      at Object.fail (node_modules/sinon/lib/sinon/assert.js:120:25)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:66:20)
      at Object.notCalled (node_modules/sinon/lib/sinon/assert.js:95:17)
      at static/js/components/SingletonsContentListing.test.tsx:172:20
```

**Comment by HussainTaj-arbisoft** [comment]
The random failures are caused by HTTP Sinon stubs with duplicate URLs. I'm not sure exactly where the issue initiates, but my experiments have led me to the following conclusion.

In `static/js/components/SingletonsContentListing.test.tsx`, whenever `contentDetailStub` at line 53 and `contentDetailStub` at line 153 are used with the same URL, the test fails.

Furthermore,
```js
singletonConfigItems = [
      makeSingletonConfigItem(),
      makeSingletonConfigItem(),
      makeSingletonConfigItem()
    ]
```

Creates three items which _can_ have the same `name` property. This property is used in the content URL. The names, by default, are generated by the `casual` generator.

There is a probability that `casual` will return the same value multiple times in a single test run, the URL relying on those values will also have a probability of being identical.

After the changes in https://github.com/mitodl/ocw-studio/pull/1700, I ran `SingletonsContentListing.test` 500 times. Not a single one failed.
