### ISSUE TITLE
" isn't being escaped in resource_link shortcode

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1238]
### Steps to Reproduce

1. Open a page in a course like https://ocw-studio-rc.odl.mit.edu/sites/peters-test-2021-09-29-1/type/page/edit/23355cd0-d1bb-473d-a2d0-820b9df7e1e2/
2. Put a double quote in the link text 
3. Publish

### Expected Behavior

- The link should publish, with double quotes

### Actual Behavior

- The double-quote isn't escaped
- so the link text is truncated at the double-quote

See https://ocw-draft-qa.global.ssl.fastly.net/courses/peters-test-2021-09-29-1/pages/ocw-studioxxx/

**Comment by ChristopherChudzicki** [comment]
Ooops. No it wasn't.

**Comment by ChristopherChudzicki** [comment]
Now it is out. #1264
