### ISSUE TITLE
Two tables got messed up by studio saves

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1259]
Two tables got messed up. I believe both commits are the first ever studio edit of the page in question... The original headers are `---` (ocw-to-hugo style) and the new headers are `###` (ocw-studio style).

- [21w.775-fall-2006 syllabus](https://ocw.mit.edu/courses/21w-775-writing-about-nature-and-environmental-issues-fall-2006/pages/syllabus/) near bottom. See commit [ef744417aeab0cad7a89ca8f59974a4899f2e0b6](https://github.mit.edu/mitocwcontent/21w.775-fall-2006/commit/ef744417aeab0cad7a89ca8f59974a4899f2e0b6)
- [21l.460-spring-2005 readings](https://ocw.mit.edu/courses/21l-460-medieval-literature-dante-boccaccio-chaucer-spring-2005/pages/readings/) near bottom. See commit [51e2088ecd0b181dcc6ed994d41140d228381e47](https://github.mit.edu/mitocwcontent/21l.460-spring-2005/commit/51e2088ecd0b181dcc6ed994d41140d228381e47)

I don't see a "real" edit in those commits, but I easily could have missed it. Saving the original content with a trivial edit works in current master branch.

### Are there more?
Unsure. Possibly not. I noticed one of these locally and found the other by searching for `anchoranchor` in markdown text.

There are exactly 3 pages on prod that contain `anchoranchor` in the markdown. Two are above. [The other one] looks(https://github.mit.edu/mitocwcontent/7.341-spring-2015/blame/main/content/pages/instructor-insights.md#L81) mostly fine, just...someone forgot to remove "anchoranchor" after fixing a messed up page.

### TO-DO:
- Figure out how this happened
- Is it still happening?
- fix the two pages in question (?)

**Comment by pdpinch** [comment]
@ChristopherChudzicki @pt2302 does this seem similar to the issue we discussed yesterday?

Do these two courses still need to be fixed?

**Comment by ChristopherChudzicki** [comment]
> Do these two courses still need to be fixed?
@pdpinch Yes. Both live pages look wrong. 

> does this seem similar to the issue we discussed yesterday?

It certainly seems similar, but there are some notable differences that might or might not be important. Namely:
>  I believe both commits are **the first ever studio edit of the page in question**... 
That means that the original markdown is coming from ocw-to-hugo. (@pt2302 That's our migration workflow from the old ocw system to the modern system.) The output of ocw-to-hugo is slightly different than what studio produces. (Example: `---` for headers instead of `###`; list items use `*` instead of `-`.) Those differences shouldn't matter, but it's possible that they do.

Interesting that the third course I mentioned is `7.341-spring-2015`. It was `7.341-spring-2022` we were discussing yesterday.

**Comment by MAbdurrehman12** [comment]
Is anyone already looking into this issue? 
I'm not sure about the context of the similar issue discussed [here](https://github.com/mitodl/ocw-studio/issues/1259#issuecomment-1231477764)

**Comment by pdpinch** [comment]
As Chris replied, the "similar" issue wasn't very similar. I haven't written it up yet, because we don't have steps to reproduce, but at least two users have opened a page to edit it, and after they save it, the table markup disappears. 

The scope of this issue now is just to fix up the two courses in question.

**Comment by ChristopherChudzicki** [comment]
Closing this... I think it probably was the same as #1486
