### ISSUE TITLE
No "anonymous" commits

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1269]
Many of our commits in github appear with an author of "anonymous" for example: https://github.mit.edu/mitocwcontent/8.421-spring-2014/commit/dab1d5141355a74015b953a055e8c1cbd0aa6222

Instead, we should have a user that reflects the automated nature of the commit. If it's easier, we could use an existing "bot" account's email address.

**Comment by mbertrand** [comment]
This can be easily changed via settings:

`GIT_DEFAULT_USER_NAME` (default "Anonymous")
`GIT_DEFAULT_USER_EMAIL` (default "anonymous@example.edu")

Anything in particular you'd like me to change them to?

**Comment by pdpinch** [comment]
`GIT_DEFAULT_USER_NAME` Engineering Bot 
`GIT_DEFAULT_USER_EMAIL` mitx-devops@mit.edu
