### ISSUE TITLE
Transcripts not displaying in newly authored courses (i.e., for video uploaded through Google Drive?)

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-studio#1295]
### Steps to Reproduce

Visit the [lecture videos page](https://ocw-preview.odl.mit.edu/courses/18100a-real-analysis-fall-2020/video_galleries/video-lectures/) and click on lectures 1 through 5. In each, e.g., [Lecture 2](https://ocw-preview.odl.mit.edu/courses/18100a-real-analysis-fall-2020/resources/18100a-lecture-2-multicammp4/), the transcript appears blank after clicking the "plus" sign. For the example above, you can see all relevant metadata for the transcript is available in [Studio](https://ocw-studio.odl.mit.edu/sites/18100a-real-analysis-fall-2020/type/resource/edit/8f7d06cd-a1ee-48af-8219-dc3ceeba55cc/?q=2).

Note, it appears this might be a broader issue for any course whose videos were uploaded through Google Drive.

- [ ] [6.801 Fall 2020](https://ocw-preview.odl.mit.edu/courses/6-801-machine-vision-fall-2020/resources/mit6_801f20_lec01_1080p/)
- [ ] [18.100A Fall 2020](https://ocw-preview.odl.mit.edu/courses/18100a-real-analysis-fall-2020/resources/18100a-lecture-2-multicammp4/)

### Expected Behavior
When a user clicks the + sign to reveal the transcript, they should see the transcript content.

### Actual Behavior
When a user clicks the + sign to reveal a transcript, the text area is blank.

### Related Issues
N/A - but this might be a know issue before @pdpinch  went on vacation.

### Screenshot or Screencast
User interface
![image](https://user-images.githubusercontent.com/1703442/166557804-68aec2d7-bd07-4264-a808-c6bc0f28d81c.png)

Studio interface
![image](https://user-images.githubusercontent.com/1703442/166558295-15589e70-6937-4628-b778-b01ee9fd0bbe.png)

**Comment by abeglova** [comment]
The file is fine on s3 https://ocw-content-backup-draft-production.s3.amazonaws.com/courses/18100a-real-analysis-fall-2020/10eRBzxaDhmhDya7nrt4G50lMys37g_7m_transcript_webvtt 

But getting the file from https://ocw-preview.odl.mit.edu/courses/18100a-real-analysis-fall-2020/10eRBzxaDhmhDya7nrt4G50lMys37g_7m_transcript_webvtt/ fails
