### ISSUE TITLE
Saving pages with image galleries in studio messes them up

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1317]
### Steps to Reproduce
1. View page "Drawing up plans for the completed models" in studio RC:
    - [studio rc](https://ocw-studio-rc.odl.mit.edu/sites/2-993-special-topics-in-mechanical-engineering-the-art-and-science-of-boat-design-january-iap-2007/type/page/edit/350c9abd-1a09-2420-0830-be0b5e07eb7a/)
    - [github rc](https://github.mit.edu/ocw-content-rc/2.993-january-iap-2007/blame/main/content/pages/image-gallery/drawing-up-plans-for-the-completed-models.md#L20)

    Note the closing `{{</ image-gallery />}}` at bottom is rendered just as `{{}}` in studio
2. Edit the page title in studio and save it

### Expected Behavior
Shortcodes should not change

### Actual Behavior
Closing  `{{</ image-gallery />}}` tag is converted to `{{}}`.

### Related Issues

This is the "legacy shortcode" (shortocdes that only exist in legacy content) issue which Alice fixed in #1013. The code in that PR expected closing shortcodes to have the `/` right before the name. I.e.
```
// legacy shortcode fix expected
{{< /image-gallery >}}
// whereas we actually have
{{</ image-gallery >}}
```
Hugo seems to tolerate both, although the hugo documentation uses the first form.

### Scope
Affects 322 pages across 75 courses. Editing those pages is probably pretty rare?

(All the other closing shortcodes we have, e.g., `{{< /anchor >}}` use the `{{< /...` form.)

**Comment by pdpinch** [comment]
Can this be closed?

**Comment by ChristopherChudzicki** [comment]
@pdpinch I've been waiting till things get released to close stuff, but maybe that's just confusing. I just verified the commit on RC, so I'll close it.
