### ISSUE TITLE
add site description to new site form

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#132]
on the mockups we show a site description:

![Screenshot from 2021-03-22 12-28-21](https://user-images.githubusercontent.com/6207644/112023951-1a2ca780-8b0a-11eb-9317-5b8ff0976d11.png)

(from https://xd.adobe.com/view/6074f9dd-fa3f-4a6c-a1fe-4d70e7d0ca78-3527/screen/43fefb77-710d-4123-92a9-4d4e9646303f/specs/)

**Comment by Ferdi** [comment]
Course description needs to have the minimal wysiwyg profile https://github.com/mitodl/ocw-studio/issues/133

**Comment by Ferdi** [comment]
Also, the source of title/description should come from the site metadata settings in the studio-config.yml file.
