### ISSUE TITLE
Broken MIT logo link

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-studio#1338]
### Steps to Reproduce

- Click MIT Logo in the navbar of ocw-studio
<img width="753" alt="image" src="https://user-images.githubusercontent.com/93309234/168294764-935b4d90-dc5e-483f-9c82-efeb50d0230e.png">

### Expected Behavior

- It should redirect to https://www.mit.edu/

### Actual Behavior

- Redirects to https://ocw-studio-rc.odl.mit.edu/sites/https://www.mit.edu and 404 is thrown

### Screenshot or Screencast

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/93309234/168294998-6325ff44-ad02-4723-af83-dfe3546ad6ce.png">

**Comment by ChristopherChudzicki** [comment]
Heh I noticed this too this morning when looking at your PR. I didn't realize you had opened this issue, so I opened #1340. Should be fixed now via #1341
