### ISSUE TITLE
No default value for license, despite being set in project starter

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1343]
This is particularly confusing because there is a default value set in the ocw-course projects 

### Steps to Reproduce

1. Add a new resource to a course by syncing it from gdrive
2. Edit the resource
3. Save the resource without changing anything

### Expected Behavior

- The resource should save and the drawer should close

### Actual Behavior

- validation error: `License is a required field`

### Related Issues

There's a similar [issue with the default value for `draft`](https://github.com/mitodl/ocw-hugo-projects/issues/173) 

I presume this is a bug on ocw-studio, because it appears that a default value is set in the course starter, at https://github.com/mitodl/ocw-hugo-projects/blob/540afebbe9b18a826ea79ee10817920e910674b1/ocw-course/ocw-studio.yaml#L175

**Comment by pdpinch** [comment]
There's a similar issue with the default setting for `draft` on resources. @MAbdurrehman12 thought it might have something to do with the way resources are created via google drive: https://github.com/mitodl/ocw-hugo-projects/pull/174#issuecomment-1126026752

**Comment by abeglova** [comment]
The default in the theme just affects the ui form in ocw-studio and is why you can't edit and save a resource without setting the license and draft value. License and draft are currently not set when resources are created from google drive and were not set for resources that were imported from legacy ocw. We need to update the code to set it when creating resources through the gdrive process and add a backpopulate command for existing resources

**Comment by ChristopherChudzicki** [comment]
> The default in the theme just affects the ui

And the default is only used for creating new resources, not updating existing resources (e.g., updating resources created by gdrive).

**Comment by ChristopherChudzicki** [comment]
@pdpinch or @abeglova Re

>  License and draft are currently not set when resources are created from google drive and were not set for resources that were imported from legacy ocw. We need to update the code to set it when creating resources through the gdrive process and add a backpopulate command for existing resources

Does the legacy data have license information that should be imported, or should we use the default license (https://creativecommons.org/licenses/by-nc-sa/4.0/) for all legacy content?

**Comment by pdpinch** [comment]
> Does the legacy data have license information that should be imported, or should we use the default license (https://creativecommons.org/licenses/by-nc-sa/4.0/) for all legacy content?

There is no license information in the legacy data. We should assume that all legacy data is https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by ChristopherChudzicki** [comment]
This is going out in https://github.com/mitodl/ocw-studio/pull/1401

**Comment by ChristopherChudzicki** [comment]
Reopening... still working on the "backpopulate" portion. New resources have license set, though.

**Comment by pdpinch** [comment]
@ChristopherChudzicki did you run the management command to backpopulate this?

**Comment by ChristopherChudzicki** [comment]
@pdpinch They've been updated in the database, but I think a management command needs to be run for them to sync with github. If they aren't used in the hugo themes, then we can probably skip that. I *think* that sync might happen automatically as part of the next mass publish, but I am not sure.

**Comment by pdpinch** [comment]
This is mainly a convenience for the course author, so they don't have to explicitly set a value every time they click save in the resource drawer. I don't see a need to push it all out to github at this time.
