### ISSUE TITLE
Limit site starter options when creating new site

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1354]
As a site author, I'd like to like to have the most common site starters appear as the default when I create a new site. 

As a site author, I'd like to have a short list of site starters to choose from, so I don't pick the wrong one by accident. 

#### Approach 

Based on [this discussion](https://github.com/mitodl/hq/discussions/29#discussioncomment-2742880), we can add a status field the `websitestarter` model with (possible) values `default`, `active` and `inactive`. 

- Only show the starters with a status of `active` or `default`. 
- Set the default value to the default starter.

**Comment by MAbdurrehman12** [comment]
Currently, multiple starters can have `default` status but only 1 of them will be shown by default. Do we need to handle this? Maybe we can restrict that only 1 starter can have a default status so if a user tries to set `default` status for another starter, we can show an error?

**Comment by Ferdi** [comment]
> Maybe we can restrict that only 1 starter can have a default status so if a user tries to set default status for another starter, we can show an error?

Good idea.

Tbh, this is probably not the most normalized way to represent the information.  A simpler way would have been a field `active` which can be `true` or `false` 
and have "default_starter" be an environment variable. 

Whatever is easier for you to implement , I would say

**Comment by pdpinch** [comment]
Well, I guess it's easier to leave it as is. 

I don't need a filter in the django admin
