### ISSUE TITLE
21W.780 F01 fails to publish

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1361]
### Steps to Reproduce

1. go to 21w-780-communicating-in-technical-organizations-fall-2001
2. publish to staging

### Expected Behavior

- course publishes

### Actual Behavior

- course fails

### Related Issues

Probably the same issue as https://github.com/mitodl/ocw-studio/issues/1308 -- a bad import from legacy plone data

**Comment by ChristopherChudzicki** [comment]
It is the same issue, `21w-780-communicating-in-technical-organizations-fall-2001` is in the list o "Sites without metadata" that @gumaerc  generated in #1308

**Comment by pdpinch** [comment]
Since this is just one course site, we should fix it up manually.

**Comment by pdpinch** [comment]
We can't close this until we get the course to publish in production.

**Comment by pdpinch** [comment]
Ok, the course will publish to staging now, but there are still some problems. 

1. There's no course image on the CHP: https://draft.ocw.mit.edu/courses/21w-780-communicating-in-technical-organizations-fall-2001/
2. In fact, there doesn't appear to be any resources in this course? https://ocw-studio.odl.mit.edu/sites/21w-780-communicating-in-technical-organizations-fall-2001/type/resource/
3. And, I can't _add_ an image because there's no button to sync resources with Google drive on https://ocw-studio.odl.mit.edu/sites/21w-780-communicating-in-technical-organizations-fall-2001/type/resource/

**Comment by gumaerc** [comment]
@pdpinch This appeared to be an issue with a bad import.  I manually corrected it by running the `create_missing_gdrive_folders` management command on it, manually uploading the course image and thumbnail and editing the metadata.  Take a look at draft and if it looks okay and can be manually corrected at this point, go ahead and publish it to production and we can close this.

**Comment by pdpinch** [comment]
Thank you!
