### ISSUE TITLE
Add widget component tests

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#138]
Our custom widget components (right now that's file upload and markdown) are only tested indirectly. We have an example starter in JS which happens to exercise all of the widget types, and then a test case which makes sure they render. We should add some widget component-specific test cases

**Comment by aliceriot** [comment]
testing the markdown component is blocked by some upstream issues, afaik the ckeditor devs are working on it but until they fix a few issues we'll have to keep mocking the ckeditor code in react tests, unfortunately.

**Comment by gsidebo** [comment]
Fair enough. Even a test where we mock CKEditor and assert that it gets certain props when we render `<MarkdownEditor />` would be helpful, I think. If we already have that test case, it should be moved into that widgets directory
