### ISSUE TITLE
can't filter backpopulate_pipelines with multiple courses

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1388]
In https://github.com/mitodl/ocw-studio/pull/1127, we added functionality to the `mass_publish` management command to filter on multiple sites either by passing a JSON file into `--filter-json` or a comma separated list into `--filter`.  The `backpopulate_pipelines` command currently does not support either of these, making it difficult to specify a specific list of pipelines to backpopulate.  We should:

 - [ ] Add `--filter-json` argument to `backpopulate_pipelines`, which should accept a JSON file in the same way `mass_publish` does
 - [ ] The `--filter` argument should accept a comma separated list of site `name` properties to filter on

**Comment by pt2302** [comment]
The `backpopulate_pipelines` command is defined [here](https://github.com/mitodl/ocw-studio/blob/master/content_sync/management/commands/backpopulate_pipelines.py).
