### ISSUE TITLE
Warn user when publishing a site with draft content

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1438]
As a course author, I'd like to be reminded when I publish a course with draft content in it. We had an issue recently where a course author published a course and couldn't figure out why their content displayed in staging, but not on the production site. 

Currently, we display warnings in the publish drawer for a variety of course issues, like missing caption files. 

#### Acceptance Criteria:

- [ ] When publishing a site with draft content, display a warning in the publish drawer below the status message. 

#### screenshot of current design for warnings

<img width="524" alt="image" src="https://user-images.githubusercontent.com/430126/183651797-58a978d7-be3c-469e-88f9-987bca826ec7.png">

**Comment by pdpinch** [comment]
If it's easier, we could display the warning when the drawer is opened, instead of waiting for when the site is published.

**Comment by pt2302** [comment]
It appears that one option is to add this as a warning to this function:
https://github.com/mitodl/ocw-studio/blob/3c70b1044d110bf716a88f9b65dbd7f10037dfe9/websites/api.py#L367 and this would be then get written to the Publish Drawer via this function:
https://github.com/mitodl/ocw-studio/blob/04bd4425cd945a1ede3f759656cae54c497348b9/static/js/components/PublishDrawer.tsx#L176-L184.

**Comment by ChristopherChudzicki** [comment]
IMO it makes sense to put the draft warning as part of the content warnings. @pt2302 from slack you said:

> although draft content isn't exactly an example of "incomplete content"

Maybe we could change the Python function's name to `get_content_warnings` or something. (I.e., any relevant warnings, not just incompleteness.) Looks like the response body property is already has the more generic name "content_warnings".
