### ISSUE TITLE
6 videos in 14.04 F22 were never submitted to 3Play for captioning

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1441]
### Steps to Reproduce

I'm not sure of the steps to reproduce, but we have six videos in the [course 14.04 F20](https://ocw-studio.odl.mit.edu/sites/intermediate-microeconomic-theory/type/resource/?q=lecture+17) that were uploaded through gdrive. I believe they were are transcoded and uploaded to YouTube successfully, but they were never captioned. 

1. Lecture 17: Existence of Equilibria
2. Lecture 4: Production and Profit Maximization
3.  Lecture 10: Ledgers and Management
4. Lecture 21: Bubbles
5. Lecture 16: Fundamental Welfare Theorems
6. Final Exam Review for 14.04 Intermediate Microeconomic Theory, Fall 2020

All the other videos in the course appear to have been captioned properly. 

When the OCW team contacted 3Play, they said:
> It appears the media file containers were added, but no services were ever ordered, and it doesn't look like the actual media files were received either.

### Expected Behavior

We expected captions. 

### Actual Behavior

Not sure where it failed, but we didn't get any captions. 

### Related Issues

1. How do we correct these 6 videos? 
2. How do we avoid this happening again?

**Comment by pdpinch** [comment]
@abeglova is going to try running the `start_transcript_job` task again on the first video.

**Comment by abeglova** [comment]
Looks like that worked https://account.3playmedia.com/files?fid=8535693&tab=details&os=0&tx=0&s=10&dfi=1&gfi=1

**Comment by abeglova** [comment]
The 6 videos have been corrected

**Comment by pdpinch** [comment]
I'm closing this, but I opened an issue for better handling of 3Play errors: https://github.com/mitodl/ocw-studio/issues/1450
