### ISSUE TITLE
replace Lecture 1 PDF file 14.772 S13

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1454]
> In this course, the lecture slides are housed within the video gallery. The PDF for Lecture 1 doesn't work, and I'd like to update it, but we don't have that functionality in Studio yet. I've already updated the updated PDF into Studio.

> https://draft.ocw.mit.edu/courses/14-772-development-economics-macroeconomics-spring-2013/resources/lecture-1-february-5-2013/

**Comment by pdpinch** [comment]
There are two related issues blocking this user:

1. I don't think there's a way to update a resource file that has already been uploaded to studio. 
2. There's no way to edit the "related resources" inside of video galleries. 

Fixing 1) seems generally useful. 

I'm not sure if 2) is a workflow we want to support in the future. A lecture video with an attached lecture slides PDF should be a resource list, not markdown stuffed into a resource.

**Comment by pdpinch** [comment]
@pt2302 have you done this one-off file update in production?

**Comment by pdpinch** [comment]
waiting on the course author to re-publish the course.

**Comment by pt2302** [comment]
The course author has re-published the course: https://ocw.mit.edu/courses/14-772-development-economics-macroeconomics-spring-2013/resources/lecture-1-february-5-2013/
