### ISSUE TITLE
Warnings when unpublishing courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1457]
As an admin who is unpublishing a course, I'd like to get a message about any site dependencies that might break when the course is removed. I would use this information to make list of sites/courses that need to be updated after the course is unpublished. 

#### Acceptance Criteria:

- [ ] since there's no UI for unpublishing, it would be OK to implement this as text returned from the unpublish API (i.e. `/api/websites/<Website.name>/unpublish/`)
- [ ] ideally, the API would return warnings about:
  - [ ] course lists in ocw-www that reference the unpublished course
  - [ ] resource lists in ocw-www that reference resources in the unpublished course
  - [ ] links in course content to the unpublished course (least important and possibly harder to do)

**Comment by MAbdurrehman12** [comment]
@pdpinch Should we proceed with unpublishing right away and a warning text returned in response? 
I wonder if a better approach will be to take the user to a `confirm unpublish` page where we have this warning text along with a button to proceed/unpublish. So the side effects can be taken care of beforehand.

What do you think?

**Comment by pdpinch** [comment]
Is there a way to implement that kind of UX when we're just using an API? There's a lot of complications with adding a web UI for this feature that I'd like to avoid for now.

**Comment by MAbdurrehman12** [comment]
Maybe what we can do is: Whenever the user hits `/api/websites/<Website.name>/unpublish/)`: This is a `GET` request, we can fetch the dependencies and show them as a text. 
Currently, since method for `GET` is not defined so we are seeing this: 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/93309234/187908637-cce61377-0271-4512-b47b-d7030c41b448.png">
So if we define it and return the dependencies as a text, it would be fine too. Post button to unpublish will still be there and we won't be having any redirection to `confirm unpublish` too which I stated above.

**Comment by MAbdurrehman12** [comment]
I'm talking about something like this: 
Whenever we go to `/api/websites/<Website.name>/unpublish` for unpublishing, we will see a message something like this: 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/93309234/187912948-cef61817-f949-4b1a-bb37-370819b617cf.png">

and when we click the `POST` button, we will see a success msg, something like this:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/93309234/187913236-cdf4490b-d825-4adc-a968-597e9e08095c.png">


Is this fine or you'd recommend something else?

**Comment by pdpinch** [comment]
This works for me, as the user of this UI. 

Do the semantics of the API responses make sense? GET returns a 200 with warnings, but POST will actually do the thing? Will your future self be able to make sense of that behavior?

**Comment by MAbdurrehman12** [comment]
> Do the semantics of the API responses make sense? 
Will your future self be able to make sense of that behavior?

I think yes.
Can't think of any issue with this approach.

> GET returns a 200 with warnings, but POST will actually do the thing?

Yeah, consider them either warnings, intimation messages, or just a text response. So it depends on how we perceive it.
Maybe someone else can also share their thoughts on this but it looks fine to me.

**Comment by MAbdurrehman12** [comment]
> resource lists in ocw-www that reference resources in the unpublished course

Should this be `resource collections`? Since we don't have `resource lists` in www

**Comment by pdpinch** [comment]
>    resource lists in ocw-www that reference resources in the unpublished course

> Should this be resource collections? Since we don't have resource lists in www

Yes
