### ISSUE TITLE
Odd behavior with bulleted list in WYSIWYG

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#147]
When you create a new piece of content with a markdown field, toggling the bulleted list in the WYSIWYG does not show the bullet in the editor. Even though the bullets are not shown in the editor, lists are saved correctly. Oddly enough, the bullets _do_ show in the UI if you are editing a piece of content. They are only absent when you are adding new content.

![ss 2021-03-24 at 12 32 11 ](https://user-images.githubusercontent.com/14932219/112347145-06fe1100-8c9d-11eb-947a-68a9d6c8e70a.png)

**Comment by aliceriot** [comment]
this is a styling issue, some styles that should only be applied to the content list pages are applied overly broadly.

in this case the list is being rendered to the dom correctly:

![Screenshot from 2021-03-24 15-48-04](https://user-images.githubusercontent.com/6207644/112374331-5867c980-8cb8-11eb-80af-18d32846ffca.png)

but `.site-page .content ul` has `list-style: none;` applied to it. I'll open a PR to fix that selector.
