### ISSUE TITLE
Remove CKEditor Underline Plugin

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1470]
### Steps to Reproduce
1. Open a page for editing

### Expected Behavior
No underline plugin

### Actual Behavior
There it is:
<img width="839" alt="Screen Shot 2022-09-06 at 10 15 09 AM" src="https://user-images.githubusercontent.com/9010790/188675766-9d1f889f-529e-477f-bb78-28461f233fa4.png">

### Related Issues

- #1084 
- https://mitodl.slack.com/archives/GQ89D0Z5M/p1662474240033869

### Other comments
The underline plugin does not work, as noted in #1084. I suspect it was originally added accidentally.

**Comment by Wassaf-Shahzad** [comment]
@ChristopherChudzicki I can do this in conjunction with my PR, if you want

**Comment by ChristopherChudzicki** [comment]
@Wassaf-Shahzad IMO we should do it separately; no need for them to be done together.
