### ISSUE TITLE
Log info when HTML -> Markdown conversion drops tables

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1478]
As an software engineer, I'd like better visibility into strange behavior reported by users.

We've had a few hard-to-reproduce issues where users would:
1. Open a page for editing; the page has tables
2. Make a trivial edit in CKEditor. Everything looks find.
3. Save the page
4. Subsequently discover that tables have disappeared from that page.

As a next step, we'd like to improve some logging.

When our CKEditor saves content, we convert from HTML to Markdown. The "Everything looks fine" part of step (2) above indicates that the HTML is correct and that any issues are happening with the html -> markdown conversion. (And this is consistent with our previous experience.)

#### Acceptance Criteria:

- [ ] If the initial HTML and the final Markdown have different "table statistics":
    - [ ] log useful information to sentry (maybe: the html string, the markdown string, and table statistics).
    - [ ] throw an error so that data is not corrupted and possibly display some sort of dialog. Ideally we'd alert the user but not close the drawer so that they could copy-paste stuff.

#### Out of Scope
Fixing the table hesienbug.

#### Other comments
`MarkdownDataProcessor` Might be a good place to insert this sort of logic. (It has access to the html and md)

**Comment by ChristopherChudzicki** [comment]
@pdpinch Are you ok with
>  throw an error so that data is not corrupted and possibly display some sort of dialog?

As mentioned on zoom, things like changing number of table cells should be fine, since the HTML will be up-to-date and should be reliable.

**Comment by pdpinch** [comment]
Ok. I'm convinced that throwing an error is OK.
