### ISSUE TITLE
One 18.102 video didn't make it to 3Play

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1483]
22 of 23 videos for course 18.102 S21 successfully submitted to 3Play. 

18102-sp21-lecture-12.mp4 was not successfully submitted. It shows up on 3Play but has no media attached, shows no duration. Looks like it tried to submit it but something went wrong. The YouTube upload went fine.
<img width="1728" alt="18102-s21-3play-fail" src="https://github.mit.edu/storage/user/6039/files/f5e33880-34fe-11ed-8114-1f6bc4fef62d">

### Related Issues

- https://github.com/mitodl/ocw-studio/issues/1441
- #1450

**Comment by pt2302** [comment]
Ran

```
import videos
videos.tasks.update_transcripts_for_video(ID)
```
on prod, where `ID` is the ID of the relevant video. The transcript has been linked in OCW Studio.
