### ISSUE TITLE
Disappearing Tables

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1486]
We initialize our HTML --> Markdown editor once globally, and if it is initialized in an area that does not support table editing, the table editing plugin never gets added. This bug is all about "on what page did the converter get initialized", which is why we've had trouble reproducing it.

### Steps to Reproduce
1. Reload OCW studio.
2. Visit a page that supports markdown editing but does NOT support tables. For example, a resource list. 

    E.g., https://ocw-studio-rc.odl.mit.edu/sites/chris-test/type/resource-list/edit/70093336-a677-47ce-806f-355bfd7c83f4/
3. Close the resource list and navigate (without reloading) to edit a page containing a table

    E.g., in that same site, pages --> "Tables!"
4. Make any trivial edit to the page markdown.
5. Save, and reopen the page you just edited.

### Expected Behavior

Tables still exist

### Actual Behavior

Tables are gone.

**Comment by pdpinch** [comment]
😳🤦🏻‍♂️

**Comment by ChristopherChudzicki** [comment]
Well, comfortingly I was wrong about it being "we" who initialized one global html -> md converter.

It's [@ckeditor/ckeditor-markdown-gfm](https://www.npmjs.com/package/@ckeditor/ckeditor5-markdown-gfm) initalizes a single turndown instance for all of their editors. Which doesn't seem great, but isn't really a problem for them, since their public API doesn't support changing the turndown instance / configuring markdown at all. We've hacked that a bit.

**Comment by pdpinch** [comment]
I believe this was fixed by #1490
