### ISSUE TITLE
Extract metadata when importing resources

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1495]
As a course author, it would save me time and reduce errors if studio would extract metadata from files when they are imported. In my authoring, I already add this metadata to the PDF files before uploading to gdrive. It's duplicate work to have to enter that metadata again into ocw-studio. 

All of the PDFs added to OCW in the past few years have had "title" and "author" metadata added to them. For example: https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/mit6_006s20_lec1/

The metadata can be viewed by opening the file in Acrobat Reader and typing command-D (on a Mac). 

<img width="724" alt="image (22)" src="https://user-images.githubusercontent.com/430126/192044353-a660d6de-6805-4ac6-9549-756a247f636f.png">

#### Acceptance Criteria:

- [ ] research options for extracting metadata from PDFs, our most common file format
- [ ] when creating new resources from files on gdrive, extract the metadata and update it in studio
- [ ] when updating existing resources from files on gdrive, extract the metadata and replace values in studio

#### Out of Scope

- Adding new metadata fields is out of scope. I don't want to add fields without knowing that they will be used, and for what.

**Comment by Ferdi** [comment]
* What are some metadata that we'd import from the file ?
* We built studio as the place to enter metadata.  Is there a reason they like to enter metadata by editing the pdf file instead ?

**Comment by pdpinch** [comment]
> What are some metadata that we'd import from the file ?

- Title, which makes sense to me. 
- The OCW team also adds author, and in Plone that was mapped to contributor. No one has been able to tell me yet what that metadata is used for. Maybe archiving. Possibly a legal obligation when the document author isn't the instructor. 
- similarly, there is a field for language (e.g. `us-en`), but I haven't seen it used anywhere yet. 

> Is there a reason they like to enter metadata by editing the pdf file instead ?

I asked this question. Here was the response (lightly edited for clarity): 

> Right now many of us use the PDF Wizard [a tool in Adobe Acrobat Pro] to [edit the metadata in] multiple files at the same time, which is much faster than opening each individual resource to add metadata. There is still some cutting & pasting involved, but it is very efficient.

> Could it function so that when you add/update the metadata in Studio and it is DIFFERENT (like an update or correction) than the existing metadata in the file OR if there is no metadata in the file, it makes the update?

Since I wasn't sure what tooling was available, I thought we would start with reading metadata and then consider writing metadata in the future.

**Comment by pdpinch** [comment]
I updated the description with an example

**Comment by Ferdi** [comment]
Thanks .  Is title the only field that we'd read from pdf and update in studio ?    What would we do with author or language ?

**Comment by pdpinch** [comment]
Just title for now. 

I'm not ready to add author and language yet, since I don't understand how they will be used.
