### ISSUE TITLE
Slack notifications for all anomalous publish statuses 

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ocw-studio#1498]
As a member of the ODL Engineering team, I'd like to know when a production live or draft pipeline fails or has any other issue preventing a successful execution.

Right now notifications are only generated on_failure. 

#### Designs and Mockups
Update the job definition to notify the slack channel of any anomalous status in job execution. 

- [ ] Implement in production

#### Acceptance Criteria:

- [ ] Peter knows when a publish fails OR errors OR other anomalous status. 
- [ ] Peter doesn't hear about the 100's of successes.

#### Out of Scope

- Email.

**Comment by pdpinch** [comment]
@Ardiea do you think we can close this?
