### ISSUE TITLE
Unpublish courses that will be archived

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1517]
Some departments don't want to publish new courses until some old courses are archived. 

The archiving process is currently happening outside of studio, but we still need to unpublish the courses from the ocw site. 

There is a list of courses to be unpublished at https://docs.google.com/spreadsheets/d/1LgVlgFnEs6yuoljLGhe583bTC0hEl5RPB80RUat7noE/edit?pli=1#gid=0

Courses on the list that have been unpublished have a unpublish date indicated in column F. 

#### Acceptance Criteria:

- [ ] unpublish the courses listed on https://docs.google.com/spreadsheets/d/1LgVlgFnEs6yuoljLGhe583bTC0hEl5RPB80RUat7noE/edit?pli=1#gid=0
- [ ] when a course is unpublish, set the unpublish date in the spreadsheet so the OCW team knows that it's done.

**Comment by pt2302** [comment]
After the PR above is merged, this management command still needs to be run on the list of courses to be unpublished.

**Comment by pt2302** [comment]
Reopening until these courses are actually unpublished in production.

**Comment by pt2302** [comment]
Downloaded the Google Doc linked above as a CSV file, and processed it with the following Python script:
```
import csv
courselist = []
with open("NextGen OCW archiving tracker - Sheet1.csv") as FIN:
    reader = csv.reader(FIN)
    for row in reader:
        if row[8].strip() == "":
            courselist.append(row[4].split('/')[-2])
print(",".join(courselist))
```

This gives the `--filter` argument to the new `unpublish_sites` management command.

**Comment by pt2302** [comment]
All of the dependencies have been resolved, all of the courses have been unpublished in production, and the Google Doc has been updated.
