### ISSUE TITLE
Fix up the resource filenames in a couple courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1527]
### Steps to Reproduce

1. Compare the file names in google drive to the published site for

course | gdrive ƒ | draft site 
-- | -- | --
[17.810](https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/) | [17.810-spring-2021](https://drive.google.com/drive/folders/1J8UeFJtpjn_2H8rMiGNmAoPnl_BiqY3K) | [game-theory-and-political-theory]()
[IDS.333](https://draft.ocw.mit.edu/courses/17-810-game-theory-and-political-theory-spring-2021) | [ids.333-fall-2021](https://drive.google.com/drive/folders/1yge0_BjLyy49vO9bdBg9Ro70ebtyBMxY) | [Risk and Decision Analysis](https://draft.ocw.mit.edu/courses/ids-333-risk-and-decision-analysis-fall-2021)

### Expected Behavior

- file names should be the same on gdrive and on the published site. 

### Actual Behavior

- additional characters are added to file names, possibly to avoid a name collision. 
- This is problematic for files that end with `lec1` for "lecture 1" and they get changed to `lec12`

### Related Issues

- https://github.com/mitodl/hq/discussions/268
- In the short term, fixing up the data would be best, so these courses can be published properly
- In the long run, we should consider changing the file naming behavior

**Comment by pt2302** [comment]
Specific resources with this issue:
For https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory:
1. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/97b5960e-068c-483c-b25d-ec0820cd7cb4
2. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/10f2771d-44f2-4f74-bec0-54321c942d66
3. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/36f3cf8f-fb85-43bf-b99a-b06287ba41a4
4. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/7d65f82b-b789-469f-b1e1-6b65f3dee49f
5. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/2831c124-3787-498f-9927-631e24912d81
6. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/b298f4a5-9553-423e-a3e2-8c6bad707ced
7. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/6e2243ba-e97f-42e3-91d7-a87358251098
8. https://ocw-studio.odl.mit.edu/sites/game-theory-and-political-theory/type/resource/edit/832884ed-8f56-4765-bcde-f00da9ccee50

For https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis:

1. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/83b78720-a3fc-490b-90be-63d1d3e26fd3
2. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/23ee0096-7d5b-47ff-877d-fdfb75ae47c7
3. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/43f02040-34bd-441c-8673-84615afa93d1
4. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/f748c1c5-328f-432c-82ec-fd03ae4d745c
5. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/899cb4d7-d34b-4404-a795-f3eefabb71f5
6. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/6899ac75-65eb-4df5-b84f-26327ad8af68
7. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/60a46f1c-ead9-41c0-9811-8cf02c93983e
8. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/bb2f8be0-bcb7-4f10-a266-8da29a097b8c
9. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/3998f522-522d-4bc0-bb15-64153ddbb72d
10. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/fcd26ee4-8870-456b-bc1c-e9ee1c1c31f7
11. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/29748dcf-0720-4e1e-8d78-f0ed2a7e3939
12. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/83fbf48f-97cc-414c-b9d7-92b4d027eeea
13. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/63bea8ae-97a8-434b-a0a5-d72f8144a884
14. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/051b8ae8-07e1-4814-9a2d-a45d973fe5e0
15. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/93e0c819-68cb-4bac-a794-5b02339f69bc
16. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/8d8dd581-fae0-4247-b07c-5a94a5626cdf
17. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/a5f24696-58a4-42c6-894b-ca5e7184b3e6
18. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/71207fc8-e60b-4e22-a04d-ea22fba0411c
19. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/320bbd0f-8ed5-4b4a-bf01-0fdbddaba733
20. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/df0362ea-2bb1-4cd3-a342-a47f6b611e7f
21. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/aa50b002-08a6-47e1-b294-f2819f12c829
22. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/a309ae05-1034-453d-aef6-ed8831d84bc2
23. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/828f34bd-f507-4886-a753-ada94de88d73
24. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/8f6b6aab-890a-4931-bac4-558c00a3dc1b
25. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/0fd79037-5b0e-485f-ba3b-fb9d87e827b7
26. https://ocw-studio.odl.mit.edu/sites/risk-and-decision-analysis/type/resource/edit/cab8e6cb-12e4-4128-a91a-f43319a44025

**Comment by pt2302** [comment]
Reopening issue until updates are made manually in production.

**Comment by pt2302** [comment]
All files were renamed.

**Comment by pt2302** [comment]
Links to `Student Project example 1 report` and `presentation slides` were removed from the `Student Projects` page, since they pointed to old content.
