### ISSUE TITLE
Combine site content forms

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#154]
`SiteAddContentForm` and `SiteEditContentForm` are implemented separately right now. This may have been to support the multi-column layout from the mockups in the "add" view, and the single column layout in the right panel "edit" view. All the same, the functionality of these forms is largely identical, and we should not be in the practice of implementing add/edit forms more than once unless there is a significant functional difference.

**Comment by aliceriot** [comment]
I believe also that the multi-column view isn't set in stone (iirc @abdulkdawson said that a single column would work fine)

**Comment by Ferdi** [comment]
I agree, the add/edit form should always be the same.

**Comment by Ferdi** [comment]
See https://github.com/mitodl/ocw-studio/issues/191
