### ISSUE TITLE
Copy old course's content to new course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1552]
As a course author, I'd like to copy the contents of https://ocw.mit.edu/courses/res-tll-008-social-and-ethical-responsibilities-of-computing-serc-fall-2021/ into my new course, at https://ocw-studio.odl.mit.edu/sites/restll-008-social-and-ethical-responsibilities-of-computing-serc/

#### Acceptance Criteria:

I don't know yet if this is a one-time request or a something that's going to be frequent enough to deserve a better interface. 

For now it seems like it would be enough to:
- [ ] make a commit in https://github.mit.edu/mitocwcontent/res-tll-008-fall-2022 with the latest version of https://github.mit.edu/mitocwcontent/res.tll-008-fall-2021
- [ ] run the management command for syncing studio with a particular git commit

**Comment by pdpinch** [comment]
I learned that this course will probably need to be copied over every year, because they expect to publish a new version every fall, building on the previous one.

**Comment by pt2302** [comment]
The https://github.mit.edu/mitocwcontent/res-tll-008-fall-2022 repo and Django database have been synced with the material from https://github.mit.edu/mitocwcontent/res.tll-008-fall-2021. Note that currently there is a single copy of all of the resources on S3 for both courses.

**Comment by pdpinch** [comment]
Well, this is what I asked for, but I've since learned that this is no what the course author needs. I'm going to discuss more with the OCW team.
