### ISSUE TITLE
Switch ocw-studio to use course-v2 in production 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1554]
#### Acceptance Criteria:

- [x] Switch the `ocw-course` `WebsiteStarter` object's `name`, `slug` and `path` properties from `ocw-course` to `ocw-course-v2`
- [x] Backpopulate individual pipelines with `heroku run ./manage.py backpopulate_pipelines`
- [x] Backpopulate the mass build pipeline with `heroku run ./manage.py upsert_mass_build_pipeline`
- [x] Run an `ocw-www` build manually from Concourse: https://cicd.odl.mit.edu/teams/ocw/pipelines/live?vars.site=%22ocw-www%22
- [x] Build an individual course and inspect the results
- [x] Run a `mass-build-sites`: https://cicd.odl.mit.edu/teams/ocw/pipelines/mass-build-sites?vars.offline=false&vars.prefix=%22%22&vars.projects_branch=%22release%22&vars.starter=%22%22&vars.themes_branch=%22release%22&vars.version=%22live%22

#### Related issues

- at some point, we should remove course-v1 code from ocw-hugo-themes and ocw-hugo-projects

**Comment by ChristopherChudzicki** [comment]
@pdpinch I am going to close this... The only thing that hasn't been done is

> at some point, we should remove course-v1 code from ocw-hugo-themes and ocw-hugo-projects

Let me know if i should not have closed it...
