### ISSUE TITLE
Unpublished instructors can be added to site metadata, causing publish failures

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#1602]
### Steps to Reproduce

- Add a new instructor to the `ocw-www` site.  Do not publish to draft.
- Edit the metadata for a course site, and try to add the new instructor in the "Instructors" section

### Expected Behavior

You should not be able to select/add the new instructor because it hasn't been published.

### Actual Behavior

You can add the new instructor.  Upon saving this to course metadata, the publish pipeline will fail.

### Related Issues

There is an earlier issue regarding this: https://github.com/mitodl/ocw-studio/issues/520
And a PR: https://github.com/mitodl/ocw-studio/pull/1023

So it's possible that the PR changes don't work for instructors for some reason, or something changed since that broke this functionality.

**Comment by pdpinch** [comment]
Is it possible that the instructor had been published to production, but not published to staging? 

Does publishing the course to staging depend on the staged (draft) version of ocw-www?

**Comment by mbertrand** [comment]
Maybe, though I didn't see evidence of that in git.  Whenever files are merged to the release branch on git, they should also be merged to the preview branch:

https://github.com/mitodl/ocw-studio/blob/master/content_sync/backends/github.py#L64-L67

```python
    def merge_backend_live(self) -> PullRequest:
        """
        Merge main branch to preview and release branches
        """
        self.merge_backend_draft()
        return self.api.merge_branches(
            settings.GIT_BRANCH_MAIN,
            settings.GIT_BRANCH_RELEASE,
        )
```        

I didn't see the new instructor file on the preview branch, but didn't check the release branch.

However, based on git commit history, it looks like there was a merge from [main to release](https://github.mit.edu/mitocwcontent/ocw-www/commits/release) 5 hours ago and 1 hour ago, ditto for [preview](https://github.mit.edu/mitocwcontent/ocw-www/commits/preview).  So that seems to be working as expected.

**Comment by mbertrand** [comment]
Publishing the course to staging does depend on the staged (draft) version of ocw-www.

**Comment by mbertrand** [comment]
According to concourse, a live build was done at [3:22 PM](https://cicd.odl.mit.edu/teams/ocw/pipelines/live/jobs/build-ocw-site/builds/283?vars.site=%22ocw-www%22) (after the new instructor was added, and after the draft course site failed) and at [11:23 AM](https://cicd.odl.mit.edu/teams/ocw/pipelines/live/jobs/build-ocw-site/builds/282?vars.site=%22ocw-www%22) (before the new instructor was added).

The most recent draft build ocw-site today was at [11:22 AM](https://cicd.odl.mit.edu/teams/ocw/pipelines/draft/jobs/build-ocw-site/builds/332?vars.site=%22ocw-www%22)

**Comment by mbertrand** [comment]
This is happening because `"cross_site": true` is missing from the site configuration for instructors (which may be deliberate considering the UI implications):

```
            {
              "collection": "instructor",
              "display_field": "title",
              "label": "Instructors",
              "multiple": true,
              "name": "instructors",
              "website": "ocw-www",
              "widget": "relation"
            },
```

Once I add it, then the instructors field will only show published instructors, but with the caveat that there will be an additional dropdown shown above it instructing the user to pick a site to choose instructors from (which should always be "ocw-www"):

![Screen Shot 2022-12-07 at 8 41 24 AM](https://user-images.githubusercontent.com/187676/206194485-acdf1033-7a0e-4f1f-8105-4c7f7eba8185.png)
