### ISSUE TITLE
Adding Sortable UI

### ISSUE THREAD

**Issue by Wassaf-Shahzad** [mitodl/ocw-studio#1635]
As per discussion on [post](https://github.com/mitodl/ocw-hugo-projects/issues/183). We need to add sortable UI based on isSortable Config.

Issues and PRs related to this issue
- https://github.com/mitodl/ocw-hugo-projects/issues/237
- https://github.com/mitodl/ocw-hugo-projects/pull/238
- https://github.com/mitodl/ocw-studio/pull/1634

#### Designs and Mockups

![173149425-af9de0bb-183a-4fd1-8c80-000ee79f1365](https://user-images.githubusercontent.com/87968618/210341656-35a58a44-d417-4ac3-95c6-b7290d45b97b.png)

#### Acceptance Criteria:

- [ ] Repeatable Content with isSortable Should be drag and dropable

**Comment by ChristopherChudzicki** [comment]
Have we decided how to handle sorting and pagination? Some options that seem reasonable to me:
1. Do not support sorting across pages, at least initially.
2. On page X, add context menu options for "Move to page X-1", "Move to page X+1"?

(2) would be similar to the GIF shown here https://django-admin-sortable2.readthedocs.io/en/latest/ (whether or not that package is actually useful to us).

**Comment by pdpinch** [comment]
@Wassaf-Shahzad it's useful to have a link to the original discussion, but we also need a more complete description for this issue: what are we doing, and how are you going about doing it.
