### ISSUE TITLE
standardize location of site resources

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1649]
Currently, the static resources of any given site are copied into the root of a given site when deployed to S3. As part of the efforts to consolidate the online and offline themes in https://github.com/mitodl/ocw-hugo-themes/issues/1013, we should standardize the location these resources are stored to be a subfolder under each site called `static_resources`. The files are stored in this subfolder in the `course-offline` theme to keep the downloaded zip file clean and not cluttered with potentially hundreds of static files, making it easier to find the `index.html` file you need to click on to launch the site. Storing the files in the same location means the URL does not need to be overridden in the offline site and a relative URL pointing to the resource relative to the site root can be used, and it will be the same URL regardless of whether rendering for offline or online use.

**Comment by pdpinch** [comment]
It's not clear to me what needs to be done here. I think the first thing to do on this issue is to create a plan and have it reviewed.

**Comment by gumaerc** [comment]
@pdpinch I should clarify that resolving this is not 100% necessary, but it is something I think we should do for better organization in addition to not having to write in different relative URLs to resources in the online and offline themes.

To summarize the problem: currently when building the online site, raw static resources from `ocw-studio` are synced to the root of each site bucket. Say I have `course-1` with `pdf-1.pdf`. That PDF will be synced to `s3://ocw-content-live/courses/course-1/pdf-1.pdf`. There's nothing inherently wrong with this, but in the offline site we gather these into a folder called `static_resources` because otherwise the downloaded course would have a mess of static files at the root. The goal here is to both consolidate the URLs written to static files as well as clean up the course sites in the live site bucket in case we decide to go forward with offering a mirror drive.

The things that need to happen are:

 - Rewrite the various paths to static assets that are stored in our `WebsiteContent` objects in `ocw-studio` to include the `static_resources` prefix, changing where studio writes new files and creating a migration to update existing ones.
 - Move existing resources in S3 into their appropriate `static_resources` subfolder.

On the surface this seems like a simple thing to do, but due to the size of OCW it could take a while for both of these tasks to complete, running the migration and moving all of the existing static files. Errors could also mean broken links.

**Comment by gumaerc** [comment]
Closing this, as it was part of my effort to "use relative URLs everywhere" and consolidate the offline and online themes into one unified there. That ended up not working out as we wanted, so this does not need to be done.
