### ISSUE TITLE
static_shared folder contains all historical webpack artifacts

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1681]
### Steps to Reproduce

 - Publish any course
 - Run the theme assets pipeline
 - Publish the course again
 - Download the offline course ZIP archive

### Expected Behavior

The `static_shared` folder only contains the webpack assets relevant to the downloaded course

### Actual Behavior

The `static_shared` folder contains all historical versions of the webpack artifacts previously built and deployed to `static_shared` in the live site bucket

**Comment by fakhar-ud-din** [comment]
@gumaerc Should we proceed with closing this?
I tested with [3-091](https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/download/) and it worked as expected.

**Comment by gumaerc** [comment]
@fakhar-ud-din Yep, closing it now.
