### ISSUE TITLE
copy offline builds to S3

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1689]
part of https://github.com/mitodl/hq/issues/785

As an admin in a geography with poor public Internet access, I'd like to be able to get a hard drive with a local copy of OCW content. I might attach the drive to a file server or to a basic web server so that my users on the local intranet might access it.

#### Acceptance Criteria:

- [ ] During the publishing of a single course, copy the offline site build artifacts to the appropriate bucket
- [ ] During a run of `mass-build-sites` with the `--offline` flag set, copy the offline site build artifacts to the appropriate bucket

**Comment by pdpinch** [comment]
The title "archive" is confusing to me. I changed this to "copy offline builds to S3"

I also updated the description to reference the epic, https://github.com/mitodl/hq/issues/785

**Comment by gumaerc** [comment]
This was mistakenly marked closed by merging https://github.com/mitodl/salt-ops/pull/1556, but it will only be closed when https://github.com/mitodl/ocw-studio/pull/1690 merges.
