### ISSUE TITLE
two videos missing in 8.06 Spring 2018

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1732]
@mbertrand @pdpinch There are two video missing in 8.06 Spring 2018. L13.4 and L13.5, which are easiest to see on this [page](https://ocw-studio.odl.mit.edu/sites/8-06-quantum-physics-iii-spring-2018/type/page/edit/775ae63a-83c3-7ea9-a86b-48e338f89741/). Let me know if there is a better way to report this or if this is the wrong place.

_Originally posted by @dseaton in https://github.com/mitodl/ocw-to-hugo/issues/459#issuecomment-1116455891_

**Comment by pdpinch** [comment]
> I don't believe anything like that exists at the moment. I think we'd have to create a resource for the video page to be created.

Can you do that from the django shell, or the django admin? There's no way to do it from studio, other than syncing a video file from gdrive. 

>how many courses have this issue? If it's just these two videos, I could try to create the resources manually.

I'm not sure, but I think it's rare. You could run a query on the production studio database for strings that have patterns similar to the two examples, something like `\d{8}\|\w*\d{8}` (8 digits followed by a pipe followed by a string with no spaces, ending with another 8 digits). 

> could you please assign this ticket to me? I don't have the access to do it myself.

👍

**Comment by HussainTaj-arbisoft** [comment]
@pdpinch I've created video resources and linked them on this [studio page](https://ocw-studio.odl.mit.edu/sites/8-06-quantum-physics-iii-spring-2018/type/page/edit/775ae63a-83c3-7ea9-a86b-48e338f89741/).

I have published the course draft. You can see the changes on the following pages:
- [the index](https://draft.ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/pages/video-lectures/time-dependent-perturbation-theory/)
- [L13.4](https://draft.ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/resources/l13-4-charged-particles-in-em-fields-potentials-and-gauge-invariance/)
- [L13.5](https://draft.ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/resources/l13-5-charged-particles-in-em-fields-schrodinger-equation/)

The author may verify these changes and publish the live version themselves.

These videos do not have captions. I had a discussion with @fakhar-ud-din and we believe the solution for issue https://github.com/mitodl/ocw-studio/issues/1518 (PR https://github.com/mitodl/ocw-studio/pull/1717) will work for this course as well.

PS:
> ...You could run a query on the production studio database for strings that have patterns similar to the two examples...

I tried different patterns on an RC dump. The example does not have a pipe, it's a lowercase L. So the pattern becomes something like `\d{8}\w+\d{8}` which results in a lot of matches even after applying some other filters.

**Comment by pdpinch** [comment]
I will follow up with the OCW team to review and publish this course.

**Comment by pdpinch** [comment]
The videos look good, and they published the course. 

But the captions and transcripts are missing. Perhaps we can run #1717 on this course?

**Comment by HussainTaj-arbisoft** [comment]
I ran https://github.com/mitodl/ocw-studio/pull/1717 for this course on RC. 3play does not appear to have transcripts for these videos. I had a discussion with @fakhar-ud-din and https://github.com/mitodl/ocw-studio/pull/1717 only fetches captions from 3play that exist.

I think we have the following possibilities:
1. If it is possible to manually generate transcripts for videos on 3play, we can do that. Then use https://github.com/mitodl/ocw-studio/pull/1717.
2. If we have the caption files, I could try to manually add them from the admin site. (Currently not sure how feasible that is.)
3. We can create a management command to trigger a transcript generation request to 3play. Using that in conjunction with https://github.com/mitodl/ocw-studio/pull/1717 should work. This is essentially option 1 with a shell command.

@pdpinch which approach do you think we should go with?

**Comment by pdpinch** [comment]
Can we run the management command now to restore these captions?

**Comment by HussainTaj-arbisoft** [comment]
> Can we run the management command now to restore these captions?

Yes, I think so. I'll try it out on RC first on Monday.

**Comment by HussainTaj-arbisoft** [comment]
Transcripts for the videos have been added and a draft was published.

You may view them here:
- https://draft.ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/resources/l13-4-charged-particles-in-em-fields-potentials-and-gauge-invariance/
- https://draft.ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/resources/l13-5-charged-particles-in-em-fields-schrodinger-equation/

Transcripts will appear on the live course once it has been published live.

@pdpinch I think this covers everything that must be done for this issue. Let me know if there is anything else. I'll make sure to move it to done and leave it for you to close after verification.

**Comment by pdpinch** [comment]
I've asked the course owner to review and publish.
