### ISSUE TITLE
Should not be able to delete a resource that is used in a site

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1754]
### Steps to Reproduce

1. Create a site
2. Sync some resources from gdrive
3. Create a resource list, like https://ocw-studio-rc.odl.mit.edu/sites/peters-test-site-for-unpbulishing/type/resource-list/edit/4509f5ad-abcc-4c51-a3f1-d0a3d9eb7464/ 
4. Delete one of the resources in the resource list from gdrive
5. Sync the site with gdrive
6. Publish the course (draft or production) 

### Expected Behavior

- sync should fail with an error similar to https://github.com/mitodl/ocw-studio/issues/1752
- the course should publish 

### Actual Behavior

- no error message: the resource is removed from the site
- publishing fails when Hugo tries to build the resource list, with the error in https://github.com/mitodl/ocw-hugo-themes/issues/1132

### Stacktrace

from this failed build, from https://cicd-qa.odl.mit.edu/teams/ocw/pipelines/draft/jobs/build-ocw-site/builds/22?vars.site=%22peters-test-site-for-unpbulishing%22#L643b9c77:19

```
selected worker: ip-10-1-3-236

streaming volume static-resources from ip-10-1-3-182

+ [ -f ../ocw-hugo-projects/ocw-course-v2/config-offline.yaml ]

+ cp ../webpack-json/webpack.json ../ocw-hugo-themes/base-theme/data

+ mkdir -p ./content/static_resources

+ mkdir -p ./static/static_resources

+ mkdir -p ./static/static_shared

+ cp -r ../static-resources/. ./content/static_resources

+ find ./content/static_resources -name *.mp4 -type f -delete

+ + wcls -l

 -1 ./content/static_resources/*.html

+ HTML_COUNT=0

+ [ 0 != 0 ]

+ touch ./content/static_resources/_index.md

+ aws s3 sync s3://ocw-content-draft-qa/static_shared ./static/static_shared --exclude *.js.map

+ hugo --themesDir ../ocw-hugo-themes/ --config ../ocw-hugo-projects/ocw-course-v2/config-offline.yaml --baseUrl / --destination output-offline --buildDrafts

Start building sites … 

hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio

Error: Error building site: failed to render pages: render of "page" failed: "/tmp/build/a69529f2/ocw-hugo-themes/course-v2/layouts/lists/single.html:14:38": execute of template failed: template: lists/single.html:14:38: executing "main" at <append (index $page 0)>: error calling append: reflect: call of reflect.Value.Type on zero Value

Total in 327 ms
```

### Related Issues

discovered while testing https://github.com/mitodl/ocw-studio/pull/1724

**Comment by gumaerc** [comment]
I think this issue should be a bit more broad than just resource lists. Resource lists are just one example of content that can be linked using the relation widget. Resources are linked to lists in the `ocw-course` starter here: https://github.com/mitodl/ocw-hugo-projects/blob/a90237cdec19e56e36f3022f225777cda7c74803/ocw-course-v2/ocw-studio.yaml#L64. Basically, I think that for anything that defines `widget: relation`, we should be preventing deletion of content actively being "related" to.

**Comment by HussainTaj-arbisoft** [comment]
@gumaerc thank you for the insight. We're currently only checking the content of type `page` for resource references. I agree that we should probably be checking for references in all "presentable" content.

A good place to start would be to create a better resource reference discovery mechanism, the current one can be found here.
https://github.com/mitodl/ocw-studio/blob/80882b3a9951ce780ebea89c1ec61b91bb693216/gdrive_sync/api.py#L645

**Comment by HussainTaj-arbisoft** [comment]
The fix in the PR https://github.com/mitodl/ocw-studio/pull/1759 focuses on courses. It checks for resource usage inside the content of a course and prevents deletion if there is any.

The content checked for usage is `page`, `resource-list`, `video-gallery`, `navmenu`, and `sitemetadata`.

I don't know how `www` uses its resources so I'm not sure if that is a concern at the moment. I'll look into it tomorrow.

**Comment by HussainTaj-arbisoft** [comment]
I've added 4 additional types to the fix https://github.com/mitodl/ocw-studio/pull/1759. The types are `resouce_collection`, `course-collection`, `promo`, and `stories`. These types are used inside `www` sites.

I believe this should cover all of the cases. I don't see anything else in the UI or the configurations.
