### ISSUE TITLE
backpopulate_archive_videos doesn't handle archive_url that starts with http://

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1755]
### Steps to Reproduce

 - Find a site with videos that have an `archive_url` that starts with `http://` and not `https://`
 - Run `./manage.py backpopulate_archive_videos --bucket ocw-website-mirror --prefix OcwExport/InternetArchive --filter <site.name here>`

### Expected Behavior

The archive URL prefix is properly removed before trying to copy the archive video

### Actual Behavior

The prefix is not removed and the copy fails

**Comment by pdpinch** [comment]
Should we just update the data for these? There's no excuse for using `http` anymore.
