### ISSUE TITLE
Remove hack from ocw import code to deal with missing uids

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#18]
Once the latest ocw-to-hugo output is on S3, remove the conditional code from `backpopulate_ocw_courses.py` that handles missing uids.

**Comment by noisecapella** [comment]
Can you provide more context? I don't see any conditional code in `backpopulate_ocw_courses.py` except argument parsing code

**Comment by mbertrand** [comment]
https://github.com/mitodl/ocw-studio/blob/master/websites/api.py#L93-L105

Might be premature though, last time I ran it there were still a handful of ocw-to-hugo output files with missing uuids.

**Comment by mbertrand** [comment]
https://github.com/mitodl/ocw-to-hugo/issues/171
