### ISSUE TITLE
Forms layout

### ISSUE THREAD

**Issue by Ferdi** [mitodl/ocw-studio#191]
As a content author , I would like a distraction free environment when authoring longer posts. 

Treat the "body" field as a special case in the UI.  When present, it should occupy its own (left) column. 

#### Designs and Mockups

* A collection with 'body' field
![Screen Shot 2021-04-06 at 8 36 55 PM](https://user-images.githubusercontent.com/125561/113794135-df388f80-9717-11eb-8633-3ab03fcc4e5a.png)

* A collection with no 'body' field
![Screen Shot 2021-04-06 at 8 38 09 PM](https://user-images.githubusercontent.com/125561/113794217-08f1b680-9718-11eb-943a-102e63909022.png)

**Comment by noisecapella** [comment]
Full mockup for reference: https://xd.adobe.com/view/7c59a2ef-de0e-4296-a073-4ba7d551d5a2-290a/screen/6da5f6f8-7bbb-4687-9c2c-957dac2903f9/
