### ISSUE TITLE
New integration tests for Google Drive, Videos, and 3Play

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-studio#1983]
# Description/Context
In the current tests, the [3Play tests](https://github.com/mitodl/ocw-studio/blob/master/videos/threeplay_api_test.py), [video task tests](https://github.com/mitodl/ocw-studio/blob/master/videos/tasks_test.py), the [Google Drive API tests](https://github.com/mitodl/ocw-studio/blob/master/gdrive_sync/api_test.py), and the [Google Drive task tests](https://github.com/mitodl/ocw-studio/blob/master/gdrive_sync/tasks_test.py) are not linked in terms of possible input/output. For example, there is no validation that the filenames passed to the video tasks test actually correspond to what filenames could look like after syncing Studio with Google Drive. This has resulted in regressions, as described here: https://github.com/mitodl/ocw-studio/issues/1964, and could have been prevented with tests that validated that the inputs to the existing tests could ever have been produced by importing the resources into Studio.

# Plan/Design

This could be a set of new integration tests, or possibly modifications to existing tests, that ensure that they could catch problems as described above.

# Out of Scope

Although not captured in this issue, there are likely other components of the OCW Studio codebase that could benefit from these kind of integration tests.

**Comment by HussainTaj-arbisoft** [comment]
I looked into what it would take to set up integration tests. To make it happen, we'd need to:

- Tweak the Celery setup to run things asynchronously
- Adjust existing tests to fit the async Celery setup where needed
- Create mocks for all the services

Putting in the effort to update the setup and create all these mocks doesn't seem super valuable right now. Our unit-test coverage is already pretty good.

Digging into the main problem and checking out the code, I'm feeling good about our unit tests in general. They're set up well with the right inputs and expected outputs. The only hiccup seems to be the caption incident. In that case, the filenames in the existing caption system are kind of tied together in a way that's different from our usual filenames and paths, which are linked through entity references. I might have missed a few things, but I'll give it another look soon.

Given all this, I think integration tests might not be the best move at the moment. I will focus on improving the existing test. In contrast to integration tests, I wonder if we could shift our focus to regression tests. Something like using Selenium in a Continuous Integration (CI) setup to test behavior seems like a more practical way to catch and prevent regressions.

---

Specifically for this issue, I think setting up a few standard fixtures should do the work to safeguard against any future mishaps related to existing captions. I'll start working on a prototype for this.
