### ISSUE TITLE
Populate file sizes for transcoded videos

### ISSUE THREAD

**Issue by HussainTaj-arbisoft** [mitodl/ocw-studio#2007]
When we sync a video from GDrive, we store its size. We then submit the video for transcoding. Once transcoding is complete, we replace the original file with the transcoded file but **we do not** update the file size metadata of the content.

## Expected Behavior

Video resources have the correct file size.

## Current Behavior

Video resources have the original file size from when they were synced from GDrive.

## Steps to Reproduce

1. Open a course in Studio.
2. Add a video file to the course's GDrive.
3. Sync the course's GDrive folder.
4. Assign the new resource a learning type.
5. Publish the course.
6. Open the download page for the course.
7. Download the video and compare the size with what is on the page.

## Possible Solution

There are two things we need to do:

1. Write code to update the file size of a resource when the original file is replaced with the transcoded file.
2. Identify the affected courses and fix the file sizes.
 
Fortunately, for point 2 above, we already have a command that works. For a course with incorrect video file sizes, we can use the following command.

```bash
./manage.py populate_file_sizes --filter <course-id> --override-existing
```

**Comment by HussainTaj-arbisoft** [comment]
Tomorrow I plan to run the command, mentioned in the description, for the courses mentioned in https://github.com/mitodl/hq/issues/2763#issuecomment-1780719705.

I've noticed that some of the courses are older and only add a few new resources. Running the command will add the file size metadata for all the resources, including the old resources.

@pdpinch, adding the file sizes for older resources doesn't seem bad. But I want to run this by you just in case. Let me know if this is something undesirable.

PS: After fixing the file sizes, I'll do a draft publish for all these courses to verify the changes. Then the final live publish will be left up to the author.

**Comment by pdpinch** [comment]
Can you give us an example of one of these older courses?

**Comment by HussainTaj-arbisoft** [comment]
> Can you give us an example of one of these older courses?

Yes, for example, this course https://ocw.mit.edu/courses/3-020-thermodynamics-of-materials-spring-2021/download/.

It has some videos with incorrect file sizes and all other older files don't have a file size at all.

**Comment by pdpinch** [comment]
Thanks for the examples. It seems like we have a lot of backfilling to do.

**Comment by HussainTaj-arbisoft** [comment]
The fix has been deployed to production. Future videos will have the correct file size.

Older affected courses also have been corrected. Their progress and status will be tracked in https://github.com/mitodl/hq/issues/2763
