### ISSUE TITLE
Create management command to backfill Google Drive for individual legacy courses

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-studio#2051]
# Description/Context
https://github.com/mitodl/ocw-studio/pull/1724 added the functionality to update and delete resources in Studio using Google Drive. However, this does not work for legacy courses, since files were not uploaded using Google Drive. The scope of this issue is to create a management command to backfill the Google Drive folder for an individual legacy course, so that files for that course can be managed using Google Drive, in the same way as for non-legacy courses.

# Plan/Design
This should be a management command that can be run for an individual legacy course that backfills the files from the relevant S3 bucket and associates them with the resource objects, as if they had initially been created via a Google Drive sync. This will involve creating `DriveFile` Django objects for the relevant files and associating them with the resources, as well as uploading the files to Google Drive using the Google Drive API.

**Comment by pdpinch** [comment]
This will help address issues like https://github.com/mitodl/hq/issues/3062 and https://github.com/mitodl/hq/issues/3237
