### ISSUE TITLE
Implement UX for successful "file"-type form submissions

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#224]
In #192 (PR #217), we implemented the UI for "file"-type config items, which lets users add/update content for those config items. There should be some feedback to the user when those forms successfully submit.

**Comment by gsidebo** [comment]
Blocked until we decide on the look and feel

**Comment by pdpinch** [comment]
We removed this UI. Files are only added to a course through syncing with google drive now.
