### ISSUE TITLE
Remove mailgun, add ol-django mail app

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#23]
As a developer, I'd like to use [ol-django](https://github.com/mitodl/ol-django/) so we are keeping up to date and share a common code base with our other applications

#### Acceptance Criteria:

- [ ] ol-django added to requirements and apps added in `INSTALLED_APPS` (#9 would accomplish this part)
- [ ] mailgun code removed, replaced with mitol-django-mail

**Comment by pdpinch** [comment]
@rhysyngsun I thought your Touchstone work (#165) would resolve this. What's left?

**Comment by rhysyngsun** [comment]
`ol-django` is a monorepo of several separately installable apps, #165 only installed the new `authentication` app, the `mail` app is a separate one so no work on this was done.

**Comment by pdpinch** [comment]
Got it. I changed the issue title to clarify.

**Comment by pdpinch** [comment]
@noisecapella can we close this?
