### ISSUE TITLE
Add and set-up Sentry

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#24]
As an admin, I'd like to have exceptions sent to sentry, especially ones arising from course import.

**Comment by pdpinch** [comment]
I don't know if the Sentry code is included in [ol-django project](https://github.com/mitodl/ol-django) -- maybe it should be.

**Comment by noisecapella** [comment]
@pdpinch the sentry logic is part of the cookiecutter so I think we should be all set there. We just need a variable for `SENTRY_DSN`

**Comment by markbreedlove** [comment]
PR to update the Sentry DSN Vault  path in `salt-ops`: https://github.com/mitodl/salt-ops/pull/1408

**Comment by markbreedlove** [comment]
I've updated Heroku with the SENTRY_DSN value for a new `ocw-studio` project that I've recently created.

The PR above is merged, so the value should be set when the automated Salt task runs to update the Heroku configurations.

My next step is to enable and tune alerts in the Sentry project.

**Comment by markbreedlove** [comment]
I've enabled alerts for the ocw-studio Sentry project so that it sends Slack notifications to our ocw-nextgen-sentry channel for new issues and ones that happen 50 times in the past day.
