### ISSUE TITLE
Github API 404 error sometimes caught by sentry?

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#246]
### Steps to Reproduce

The `retry_on_failure` decorator should retry a failed github API request up to 3x (separated by a second each) before raising an exception, because sometimes a 404 error is raised if a request is made to a newly created repo too soon.   As long as it hasn't failed >3 times, the exception should be caught and ignored by the app and sentry.

### Expected Behavior

Website update succeeds, no error reported by sentry despite 1 or 2 404 API responses.

### Actual Behavior

Website update seemed to succeed, but error reported by sentry.

https://sentry.io/organizations/mit-office-of-digital-learning/issues/2378302005/?project=1413655&referrer=slack

**Comment by pdpinch** [comment]
The original error hasn't happened again in some time. 

This error might be the same thing? But it doesn't happen very often either. 

https://sentry.io/organizations/mit-office-of-digital-learning/issues/2825543024/?project=5739976&query=is%3Aunresolved+404&statsPeriod=14d

Do you think we can close this?

**Comment by mbertrand** [comment]
Looks like the most recent errors occurred because of an issue with parentheses in the repo name, which should now be fixed.
