### ISSUE TITLE
Remove course id from filepaths in imported OCW course sites

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#260]
When importing OCW course sites, we prepend `WebsiteContent.course_filepath` values with the full course id.

Example: `1-040-project-management-spring-2004/content/sections/syllabus.md`

The prepended course id is unnecessary for this project, and is almost definitely a relic from the way our pre-Studio OCW course site builds work. The example above should instead be `content/sections/syllabus.md`

If PR #259 is merged before this is complete, this issue should also include removing the prepended course id from `WebsiteContent.dirpath` values.

**Acceptance criteria:**
- Data migration added to remove course id prefixes from `content_filepath` values
- (If #259 is merged) Data migration added to remove course id prefixes from `dirpath` values
- Course site import logic updated to avoid prepending course id to `content_filepath`/`dirpath` values

**Comment by gumaerc** [comment]
Closed by https://github.com/mitodl/ocw-studio/pull/513
