### ISSUE TITLE
add support for linking to collections in other websites using Relation widget

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#288]
As a site configuration author, I'd like to be free and unconstrained as to which collections I might link. It matters not to me whether they be here or there, in this site or that, I want simply that they be present and linkable.

For this field we essentially want three ways to use it:

1. Linking to a specified collection located in the same website. This is the use-case supported by what we've already implemented.
2. Linking to a specified collection in a specified website. This use-case is supported by the code I wrote here, and would support the use-case you mentioned Ferdi of having a list of departments in ocw-www and then wanting to reference them from within a course.
3. Linking to content within a user-specified website and collection. This would require two dropdowns: one to pick the website from a list of websites, and a second to pick the collection _within_ that website to which we want to be able to link. For example, consider the `resource` collection that we have in our example course config. If we wanted to support linking from one course to resources in another course, a course author would need to be able to select the course, then select linking to the `resource` objects within that course, and then finally get a list of all those resources to be able to select the relevant one.

For these three scenarios we want to support, we can set a `website` value on the ConfigField for the Relation field. Then in the UI we can switch on the `website` value to present relevant functionality to the user.

- if not present, then fetch the items in the `collection` within the same website.
- if specified, then fetch the items in the `collection` within `website`
- if `"*"`, then show the user a drop-down for picking a website. Once they pick a website, show another dropdown to pick which collection within that website. Then, once they've picked a collection, show the entries in that collection so that the user can pick from them.

One slight complication is that to support the "global" / "wildcard" config I think we'd want to store not just the `text_id` of the linked-to content but also the website and collection that it is from, so that we can then repopulate the UI correctly when editing later, etc.

#### Acceptance Criteria:

- [x] Optional configuration on the Relation field for which website the collection is within (if it's not set, assume that it's in the same website)
- [x] make the API call to the content listing API based on the website configuration (if present)
- [x] implement the simple, directly specified case (#306)
- [x] #813 
- [x] update Relation field documentation to reflect these changes

**Comment by aliceriot** [comment]
@pdpinch I was just wondering if you had thoughts about the UX here, especially for the 'wildcard' case (where the user can pick a website and then get a list of content in that collection). I was thinking we could have three fields, like

1. website
1. collection
1. content

where after 1 is populated by the user we get info about that website so we can show options for 2, then once the user has made a selection of collection then we fetch and then show options for picking the actual content. These fields could look something like our current 'object' field, i.e. somewhat clearly visually grouped together:

<img width="569" alt="Screen Shot 2021-06-30 at 3 35 11 PM" src="https://user-images.githubusercontent.com/6207644/124020828-cfe47d80-d9b8-11eb-927a-d8d9b187ec8b.png">

Anyhow, I was going to get started on this, and just wondering if you had any thoughts.

**Comment by alicewriteswrongs** [comment]
just updated the documentation, I think this issue is good to close now.
