### ISSUE TITLE
Create github webhooks with secret keys, add `GITHUB_WEBHOOK_KEY` env variable

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#300]
#### Summary

Related to #297.

For the https://github.com/mitodl/ocw-hugo-projects repo, create a webhook for each environment:
  Payload URL: `https://<CI/RC/PROD domain>/api/starters/site_configs/`
  Content-type: `application/json`
  Secret: secure non-blank value
  Events: pushes
  
For each environment, add:
  `GITHUB_WEBHOOK_KEY=<secret>`

#### Applicable Environments

- [ ] Apply configuration to CI
- [ ] Apply configuration to RC
- [ ] Apply configuration to Production

**Comment by blarghmatey** [comment]
Addressed by https://github.com/mitodl/ol-infrastructure/pull/192 and https://github.com/mitodl/salt-ops/pull/1423

**Comment by pdpinch** [comment]
Can this be closed?
