### ISSUE TITLE
Epic: add support for user-defined collections of websites

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#309]
As a course author, I'd like to write a list of courses similar to this one: https://ocw.mit.edu/courses/energy-courses/

To support this, we want to add support for defining a 'collection' of websites. This will let a content author add a new list and add websites to it, using our existing APIs to build out an editing UI.

These collections can then be added as embedded content to our WYSIWYG editor, which will allow content authors to publish pages like the one linked above (for instance in the ocw-www 'entry' site).

#### Acceptance Criteria:

- [x] #315
- [x] #334
- [x] #316
- [x] #356 
- [ ] #371
- [x] #357 
- [ ] #317 
- [ ] #355 
- [x] #376
- [x] #396

**Comment by aliceriot** [comment]
@Ferdi @pdpinch quick question, should a site content author be able to add a course to a WebsiteCollection more than once?

**Comment by alicewriteswrongs** [comment]
This epic concerned our earlier implementation of the feature - I'm going to close this so we don't get confused (or so I don't get confused anyway!)
