### ISSUE TITLE
Permissions for site creation and editing

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#33]
- Only Django users of certain group should be able to create `Website`s of a given type (ie `course`)
- A user can be a member of 1 or more `Website`s , with a different role/privilege on each. For example, a user can be an “admin” on site1 but just an “editor” on site2

Implement using Django's built-in permission system, Rest framework permissions, django-guardian object-level permissions as necessary.

<img width="460" alt="Screen Shot 2021-02-05 at 2 57 20 PM" src="https://user-images.githubusercontent.com/187676/107082647-805fa400-67c2-11eb-8076-578877a71297.png">

**Comment by mbertrand** [comment]
@Ferdi @pdpinch :

Does this sound right:

- Both website admins and editors can edit the basic site info (title etc), publish changes to the site, and add/modify/delete WebsiteContent.
- Only website admins can add other admins/editors and unpublish the website.
- Only the website creator (or no one at all) can delete the website.

**Comment by pdpinch** [comment]
- I assume we would give the editor role to OCW staff, and I think we would want them to be able to unpublish courses. 

- I think we might want a role that can edit and preview but not publish a course to the OCW site, for example an instructor or a course TA who is making edits. 

The rest of what you said sounds right to me.

**Comment by mbertrand** [comment]
I could use some clarification on the above.  

Should OCW staff users be able to edit & unpublish all OCW websites?  Or just specific ones?

" a role that can edit and preview but not publish a course " - is this a role below "Editor", ie "Contributor"?  Editors can edit, preview, and publish; collaborators can edit, preview, but not publish; admins can do the same as editors plus add/remove editors and contributors.

Here is the preliminary RFC by the way - https://docs.google.com/document/d/10nDan_aTPNV0sFdWXoGqYmR1mIva41QXaDanO3om2xk/edit?usp=sharing
