### ISSUE TITLE
Include WebsiteContent.file url in metadata written to the backend (github)

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#331]
The serializers used for writing content to files in github should insert the file url into the metadata for any `WebsiteContent` objects that have uploaded files, using the field name as specified in the site config.

The management command for syncing from github back to the database should also properly handle the file url in the metadata.

**Comment by pdpinch** [comment]
Is this necessary for linked images, like the ones in the testimonials in ocw-www?

**Comment by mbertrand** [comment]
Yes, this should have been closed by merging https://github.com/mitodl/ocw-studio/pull/333, entered the wrong issue # in the description.
