### ISSUE TITLE
Need a Fastly distribution for preview & published S3 buckets

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#332]
#### Summary

Files stored in ocw-studio S3 buckets (preview, published) should be accessible via Fastly URL's.

#### Applicable Environments

- [ ] Apply configuration to CI
- [ ] Apply configuration to RC
- [ ] Apply configuration to Production

**Comment by pdpinch** [comment]
@mitodl/devops @mbertrand can this be closed?
