### ISSUE TITLE
tab view for courses, collections

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#371]
In our mockups for the WebsiteCollection UI we have a tabbed view for 'Courses' and 'Collections':

![Screen Shot 2021-07-01 at 10 26 18 AM](https://user-images.githubusercontent.com/6207644/124140776-c7428480-da56-11eb-84c0-87c320763741.png)

We need to implement this or some kind of navigation UI for collections.

**Comment by pdpinch** [comment]
I don't think we need this anymore.
