### ISSUE TITLE
Delay fetches in incremental search for course select in collections UI

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#394]
Related to #391

Currently the course selection UI in the edit collections dialog makes an API request on each keypress. We should figure out how to delay fetches so that they go out every 300 milliseconds or so, for example. https://stackoverflow.com/questions/42217121/how-to-start-search-only-when-user-stops-typing#answer-61629055

**Comment by aliceriot** [comment]
we should be able to just use something like `_.debounce`

I'd add it in to #391 but I don't want to have to rewrite tests :)

**Comment by noisecapella** [comment]
I added a [debouncedFetch](https://github.com/mitodl/ocw-studio/pull/402/files#diff-57de335e123528cc1d0c582d540c7bdeb98c2ef63b14f46f4180da20d8cac810R56) function in my PR. Once that merges it should be simple enough to use as a drop-in replacement for this issue
