### ISSUE TITLE
React warning when adding the same course multiple times in collection course selection UI

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#395]
Related to #391 

If the user adds the same course multiple times to the collections course selection field it will cause a react warning since the `key` prop needs to be unique in the list. It may be easiest to filter out courses already added from the dropdown so they can't be added again. However there is a product decision which needs to be made since there could be a use case for having multiple instances of a course in a collection.

**Comment by alicewriteswrongs** [comment]
@pdpinch @Ferdi wondering what your thoughts are on this - is there a use-case for adding the same course to a course collection more than one time?

**Comment by pdpinch** [comment]
No, no reason to have the same course twice in the same list.

**Comment by alicewriteswrongs** [comment]
if we want to add this constraint, we'll need to add it as a general constraint on our relation field
