### ISSUE TITLE
use ocw-hugo-projects course starter and remove localdev version

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#457]
In `ocw-studio`, we are currently using `localdev/configs/ocw-course-site-config.yml` as a course site starter for importing legacy OCW courses and testing. Recently, we have been working on the [`ocw-hugo-projects`](https://github.com/mitodl/ocw-hugo-projects) repo to store Hugo and `ocw-studio` starter configs for OCW related projects.  One of the starters we've created there is the course site starter that should be used moving forward.  Rather than maintaining a separate yaml file in this repo, we should use the starter from `ocw-hugo-projects` moving forward.

#### Acceptance Criteria
 - Upon provisioning `ocw-studio`, the Github webhook code is fired and the starters from `ocw-hugo-projects` are pulled in and imported if they do not exist, or are updated if they are out of date
 - The course starter used in OCW legacy course import and testing should be configurable with a slug that is matched against what is pulled in from `ocw-hugo-projects`
 - The `localdev/configs/ocw-course-site-config.yml` file should be removed

**Comment by aliceriot** [comment]
if we transition to the `.yml` file in ocw-hugo-projects, what's the workflow for adding a new configuration option and developing locally with that change look like?

**Comment by gumaerc** [comment]
@aliceriot Locally, you can set `GITHUB_WEBHOOK_BRANCH` to any branch you create in `ocw-hugo-projects` and expose your local instance of studio with `ngrok` or something similar and every commit you make will fire a webhook that will trigger studio to ingest the starter configs there. You can then make a PR with your changes in `ocw-hugo-projects` and as it goes through the paces (`release-candidate` to `release`) the webhooks will file and automatically update the RC and prod instances respectively. It's not as convenient as just having the local yaml file just there in `ocw-studio`, but since the configs in `ocw-hugo-projects` are what we'll be using for Concourse builds moving forward it creates an awkward situation where legacy courses are imported and assigned to this other starter with a different slug that has to be updated manually to reflect changes merged in `ocw-hugo-projects`. I'm not exactly sure what the perfect solution is, but having these two starters with different slugs that aren't automatically in sync with each other feels sloppy and prone to human error.

**Comment by gumaerc** [comment]
For testing local changes to the starter, you could also import the config from Github into your local instance as is and then manually copy / paste your changes as you're testing them into Django admin.  Then when you're ready, make the PR in `ocw-hugo-projects` to update the config and as it goes through the release process the starters will automatically be updated across envorinments.

**Comment by gumaerc** [comment]
Another thought; maybe we could have a management command to manually update a starter by slug and point it to a local file specifically?  Something like `./manage.py update_starter <STARTER_SLUG> <STARTER_PATH>`?  That way you could make the changes in your local copy of `ocw-hugo-projects` and updating it in your local instance of studio would be as simple as having a terminal open with that command ready and up->enter to refresh it?

**Comment by aliceriot** [comment]
Any way this could be automated and not require fiddling about with git URLs or messing around in another repo to try out a little config change would be good in my book I think. Editing the `.starter` JSON field on a `Website` record can work I think, but it would be nice to have some well-documented management commands or admin functionality for fetching things from `ocw-hugo-projects` and whatnot as well.

One thing we should be sure of I think, is that if we make a change to work with the `ocw-hugo-projects` starters by default we should put some time and effort into the tooling so that it's as painless as possible for local development, so that things are explained well and easy to configure, work by default, and so on.

**Comment by gsidebo** [comment]
@aliceriot FYI you can define local starter projects: https://github.com/mitodl/ocw-studio/tree/master/localdev. This lets you define your own configs then "import" them via management command

**Comment by gsidebo** [comment]
> Another thought; maybe we could have a management command to manually update a starter by slug and point it to a local file specifically? 

@gumaerc If I'm understanding correctly, the `override_site_config` already takes care of that
