### ISSUE TITLE
Youtube API configuration for OCW Studio production

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#486]
#### Summary

`YT_PROJECT_ID`
`YT_CLIENT_ID`
`YT_CLIENT_SECRET`
`YT_ACCESS_TOKEN`
`YT_REFRESH_TOKEN`

- Create a new project at https://console.cloud.google.com/apis/dashboard
  - Use the project ID  as the `YT_PROJECT_ID` value
- Enable the YouTube Data API v3 for your project
- Create an OAuth client ID for the project (type: ``Desktop client``)
  - You may need to create an oauth consent screen if prompted; make sure to publish it.
  -  Use the client id and secret as  `YT_CLIENT_ID` and `YT_CLIENT_SECRET`)
- Run the following Django command from this PR branch to generate values for `YT_ACCESS_TOKEN` and `YT_REFRESH_TOKEN`:
  `python manage.py youtube_tokens`

Related to #480, #484

#### Applicable Environments

- [x] Apply configuration to RC
- [ ] Apply configuration to Production

**Comment by shaidar** [comment]
This is now applied to CI/RC Heroku apps

**Comment by mbertrand** [comment]
This will still need to be done for production when ready to go live.  

It should be possible to use the same oauth app as for RC (same values for `YT_PROJECT_ID`, `YT_CLIENT_ID`, and `YT_CLIENT_SECRET`).  Run `python manage.py create_yt_authokens`, copy the resulting URL in a browser while logged in under the appropriate account, and select the 'MIT OpenCourseWare" channel when given a list of account options:

<img width="485" alt="screen_shot_2021-10-26_at_12 08 26_pm" src="https://user-images.githubusercontent.com/187676/146220383-aae2e2ab-bb90-4c2f-b33e-632c98fe7007.png">

Alternately, we can create a separate oauth app for production.  Advantage: it will have its own quota instead of sharing with RC.  Disadvantage: will have to fill out all the required forms again to get the new app verified, quota increased, etc.

**Comment by pdpinch** [comment]
We should set this up before Monday, 2/14

**Comment by mbertrand** [comment]
Now we can!
