### ISSUE TITLE
serialize instructors when exporting courses

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#490]
When a course site using the `ocw-course` starter is currently exported, instructors referenced with a relation widget in the course data template are serialized like this:

```
  "instructors": {
    "content": [
      "8d86c853-1a70-49ed-ba3c-8db2bd12026b"
    ],
    "website": "ocw-www"
  },
```

Instead of just publishing the UID of the instructor, the appropriate data should be fetched and serialized so it looks more like this:

```
  "instructors": [
    {
      "instructor": "Prof. Mark Jarzombek",
      "url": "/search/?q=%22Prof.%20Mark%20Jarzombek%22",
      "first_name": "Mark",
      "last_name": "Jarzombek",
      "middle_initial": "",
      "salutation": "Prof.",
      "uid": "5cf93f985f34b91ce2c3e6b5c1371dc5"
    },
    {
      "instructor": "Prof. Meejin Yoon",
      "url": "/search/?q=%22Prof.%20Meejin%20Yoon%22",
      "first_name": "Meejin",
      "last_name": "Yoon",
      "middle_initial": "",
      "salutation": "Prof.",
      "uid": "42b97d24f31c4d722e7094b7ef7abe48"
    }
  ],
```

**Comment by Ferdi** [comment]
@gumaerc can the theme do the fetching ?
Otherwise it would be hard to keep the relation widget generic

**Comment by gumaerc** [comment]
@Ferdi The issue with that is that Instructors are stored in `ocw-www` and not the course site.  So, all we have in the course site at the moment is the UID.  The theme could potentially fetch them with `getJSON` but that would add an API request to every course build which could slow things down and add a dependency on `ocw-studio` being online to complete the build.

**Comment by pdpinch** [comment]
@gumaerc I think we can close this, since we chose to go the route of using getJSON with the static API output from ocw-www.
