### ISSUE TITLE
Menu items not exporting with urls

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#497]
### Steps to Reproduce

This may be tricky to reproduce but you can see the issue here:

 - Go to [here](https://ocw-studio-rc.odl.mit.edu/sites/res-8-001-applied-geometric-algebra-spring-2009/type/menu/) on RC. You should see a menu.
 - If you click publish you should see published results on [github](https://github.mit.edu/ocw-content-rc/res.8-001-spring-2009-2/blob/main/config/_default/menus.yaml). The URL is actually originally present in the output but that's only because it was stored in the metadata when the course was originally imported.
 - On the menu page, swap the order of the two menu items, then click Save. If you look at the updated metadata you should see no `url`, only the `identifier`. I think this is the right behavior.
 - Go to the published markdown on RC for menu.yaml. You should not see any 

I investigated and I think the problem is that our UUID logic is faulty. For example one of the links is `67a3ef1f-0e3b-a873-11f9-3fb9ee2e9ecb`. `is_valid_uuid` says this is not a valid uuid because these two don't match up:

    In [7]: UUID("67a3ef1f-0e3b-a873-11f9-3fb9ee2e9ecb", version=4)
    Out[7]: UUID('67a3ef1f-0e3b-4873-91f9-3fb9ee2e9ecb')

Which means we aren't treating them like internal links.

I think there are two bugs here:
 - Either we detect the UUID differently (regex?) or use the "external-" prefix to figure out which links are internal.
 - We should not be adding a URL during import if there is an internal link. That is added during export. This bug covered up the other bug.

**Comment by gumaerc** [comment]
Based on some research @noisecapella and I did today, the issue here is specifying `version=4` in `main.uitls.is_valid_uuid`.  Even when UUID's are imported and parsed specifying `version=4`, they differ slightly.  Removing the version specification from `is_valid_uuid` fixes the issue, but I'm not sure if the version comparison is important.

**Comment by gumaerc** [comment]
With local modifications to `is_valid_uuid` to not specify the version, I was able to get a menu to successfully publish URL's, but studio decided to publish it to a new repo for some reason: https://github.mit.edu/ocw-content-rc/12.010-fall-2011-2/blob/main/config/_default/menus.yaml
