### ISSUE TITLE
Menu widget isn't working

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#502]
### Steps to Reproduce

Go here: https://ocw-studio-rc.odl.mit.edu/sites/res-7-001-pre-7-01-getting-up-to-speed-in-biology-summer-2019/type/menu/

### Expected Behavior

It should load the page

### Actual Behavior

It doesn't

### Stacktrace

![Screenshot from 2021-08-18 14-01-13](https://user-images.githubusercontent.com/863262/129948953-19352b4e-b15c-4b0f-bfc2-e118ded5945f.png)

**Comment by gumaerc** [comment]
This has to do with imported courses having an external menu item in them.  I think maybe the imported UUID isn't prefixed with `external` like studio does when it generates them.
