### ISSUE TITLE
Send notifications to site collaborators when a video upload to Youtube is complete (or fails)

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#533]
As a site collaborator, I'd like to be notified when a video has been successfully uploaded & processed on Youtube.
It would also be helpful to receive a notification if a Youtube upload fails for any reason.

#### Designs and Mockups
Subject:  [OCW Studio] video uploaded to Youtube
Message: The video "<original_video_filename>" for your site "<site_name>" has been uploaded to Youtube and is available to view at <youtube_link>.

Subject:  [OCW Studio] video error uploading to Youtube
Message: The video "<original_video_filename>" for your site "<site_name>" could not be uploaded to Youtube.  Please contact OCW support for help.  Error: 

<error_message>

#### Acceptance Criteria:

- [ ] All site collaborators receive a notification when a video is successfully processed on Youtube
- [ ] All site collaborators receive a notification when a video fails to upload to Youtube

**Comment by pdpinch** [comment]
I updated the subject line a bit. I thought maybe it would be good to include the video filename and/or sitename in the subject line, but decided against it.
