### ISSUE TITLE
import_ocw_course_sites does not reliably complete

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#550]
Even with the 2x dyno I am seeing the celery process killed and the import stuck partway through. We need to figure out how to cut memory use, or alternatively pay more for a larger dyno

**Comment by pdpinch** [comment]
@gumaerc I remember you said that some of the courses have embedded HTML transcripts. Would it help the memory issues (enough) to omit those HTML transcripts? I don't think we need those in the new design and, even if we did, there are better & easier ways to regenerate them (for example, HTML is an output format from our captioning vendor, 3Play)

**Comment by pdpinch** [comment]
@gumaerc do you think we can close this now?

**Comment by pdpinch** [comment]
@gumaerc can we close this?

**Comment by gumaerc** [comment]
Yes, sorry.
