### ISSUE TITLE
Copy all file resources from the legacy ocw bucket to the ocw studio bucket

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#561]
All pdfs, images, non-youtube videos, and other files in the OCW legacy S3 bucket need to be copied over the OCW Studio bucket, under appropriate site-specific paths, so that they are included in preview/publish tasks.

#### Designs and Mockups

-  Add an additional option on the existing import command to copy all legacy ocw files (videos, pdf's, images, docs, etc) from the legacy ocw bucket to the OCW Studio bucket, using the correct S3 object prefix in the destination.
- Modify the ocw import code so that the `WebsiteContent.file` field is populated correctly, pointing to the appropriate OCW Studio S3 url.

**Comment by pdpinch** [comment]
@mbertrand can we close this now?
