### ISSUE TITLE
Remove video button from wysiwyg editor 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#576]
Once we are able to embed (on link) to video resources using the resource picker, we can remove the video embed button.

**Comment by alicewriteswrongs** [comment]
for future reference: the video embed icon in ckeditor is the icon for the 'media embed' plugin (see [docs](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html)). With our integration of resource links and embeds we've essentially implemented a subset of the functionality there that we need. If in the future we need / want a wider range of embeds (like vimeo videos, spotify playlists, or whatever) it might be worthwhile to look into re-enabling this, with the understanding that we'd also need to write a markdown support plugin for it.
