### ISSUE TITLE
Newest courses API is broken on CI

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#59]
### Steps to Reproduce

Go to https://ocw-studio-ci.odl.mit.edu/api/websites/?type=course
Go to https://ocw-studio-ci.odl.mit.edu/api/websites/

### Expected Behavior

- Get list of published websites, of type=course
- Get list of published websites, of any type

### Actual Behavior

- Get no results
- Get list of published websites,

**Comment by gsidebo** [comment]
All set. Just caused by data loss
