### ISSUE TITLE
Add collaborator screens

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#60]
**Depends on permissions PR: https://github.com/mitodl/ocw-studio/pull/49** 
Wireframes: [list page](https://lucid.app/lucidchart/6be33dd8-f7db-47f8-8af8-338255f23c3c/edit?shared=true&page=BYpVt0I~zBD_#?folder_id=home&browser=icon), [create page](https://lucid.app/lucidchart/6be33dd8-f7db-47f8-8af8-338255f23c3c/edit?shared=true&page=o3pVIT4811zL#?folder_id=home&browser=icon)

The REST APIs to support these screens can be added in a separate PR or as part of this one

**Acceptance criteria:**
- Listing and create/edit pages added
- Create/edit page has simple text input (required) and dropdown for user and permission group respectively
  - Text input will be for user email (case-insensitive). Non-existent emails should result in a validation error message under the text input. We may want a more sophisticated input for finding users in the future, but that can be added later
Saving this form should add the appropriate groups/permissions for the given user
- Listing page shows all users with website-specific permissions/groups
  - Show the current permission level/group for each user in the list as simple text
  - If the logged-in user can change website-specific permissions, place an edit icon next at the end of the line. Clicking on that icon should take you to the create/edit page to edit that user's permission level
  - Garbage can/large X icon should be shown if the current user has the permission level to delete users. We should ask for confirmation before going through with the delete

**Comment by mbertrand** [comment]
> "If the logged-in user can change website-specific permissions, place an edit icon next at the end of the line"

Should an editor, who is not allowed to add/change collaborators, even be able to view this page?  Any benefit to an editor knowing who admins & other editors are?

> "If the logged-in user can change website-specific permissions, place an edit icon next at the end of the line. Clicking on that icon should take you to the create/edit page to edit that user's permission level"

The [list page design](https://lucid.app/lucidchart/6be33dd8-f7db-47f8-8af8-338255f23c3c/edit?shared=true&page=BYpVt0I~zBD_#?folder_id=home&browser=icon) shows a dropdown instead next to the user's name, presumably changing this will instantly change the user's permission level, without the need to go to the create/edit page?  Which approach is preferred?

**Comment by gsidebo** [comment]
@mbertrand 

> Should an editor, who is not allowed to add/change collaborators, even be able to view this page? Any benefit to an editor knowing who admins & other editors are?

I think it's fine to go with whatever is less work between (a) removing the collaborators link and preventing editor users from accessing the page directly, and (b) showing the page, hiding the edit links, and preventing access to the collaborator edit form page

> The list page design shows a dropdown instead next to the user's name, presumably changing this will instantly change the user's permission level, without the need to go to the create/edit page? Which approach is preferred?

I asked Ferdi about that & we agree that opening a separate page with an edit form is preferred

**Comment by mbertrand** [comment]
Any particular order the users should be sorted by?  For now the default is `User.name` (ie "firstname lastname")

**Comment by gsidebo** [comment]
Yeah, no need for anything beyond the default at this point
