### ISSUE TITLE
Update has_unpublished_* flags when content state is updated

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#655]
We merged https://github.com/mitodl/ocw-studio/pull/644 at about the same time as adding the `has_unpublished_draft` and `has_unpublished_live` flags were added, which indicate to the frontend what needs to be published. We should update the content sync code to set those flags to `True` so that the frontend sees that there is a publish that needs to happen

**Comment by noisecapella** [comment]
I talked with @mbertrand and he suggested we update `trigger_pipelines` to run `publish_website_backend` or `preview_website_backend`, and also update whatever status fields we need to there. I think that should be it to call this issue done

**Comment by noisecapella** [comment]
@mbertrand not sure what's left here so I'll reassign to you

**Comment by mbertrand** [comment]
The `reset_sync_states` command will update those status fields by default unless `--skip_sync` is passed.
