### ISSUE TITLE
Show a link to a Website's Google Drive folder on the Resources tab

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#718]
As a user, I'd like a link to a site's Google Drive folder on the Resources page for easy access. 

<img width="755" alt="Screen Shot 2021-10-21 at 8 48 08 AM" src="https://user-images.githubusercontent.com/187676/138280801-b32a38e4-967e-416e-a3e8-4b84941e07a5.png">

**Comment by alicewriteswrongs** [comment]
yes!
