### ISSUE TITLE
Set page titles

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#724]
Page history isn't very useful without page titles. 

![Screen Shot 2021-10-20 at 3 50 34 PM (2)](https://user-images.githubusercontent.com/430126/138162214-a4a03e0e-5882-4724-a197-4b879a88813f.png)

**Comment by alicewriteswrongs** [comment]
@pdpinch do we have an idea what the page titles should be? My stab at it would be something like:

| url | name |
| --- | --- |
| `/` | `"OCW Studio"` |
| `/sites` | `"OCW Studio \| Sites"` |
| `/sites/$SITENAME` | `"OCW Studio \| ${SITE_TITLE}"` |
| `/new-site/` | `"OCW Studio \| New Site"` |
| `/sites/$SITENAME/type/$CONTENTTYPE` | `"OCW Studio \| ${SITE_TITLE} ${pluralize(CONTENTTYPE)}"` |
| `/sites/$SITENAME/collaborators` | `"OCW Studio \| ${SITE_TITLE} Collaborators"` |
| `/collections/` | `"OCW Studio \| Collections"` |
| `/privacy-policy/` | `"OCW Studio \| Privacy Policy"` |

**Comment by pdpinch** [comment]
That will work, at least for a first pass.
