### ISSUE TITLE
mass-publish sites

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#730]
Currently, we have the `reset_sync_states` management command which can be used to reset the `ContentSyncState` for sites en-masse.  It has the  `--sync_backends` option which allows for forcing the sites to be published to their configured backend.  What's missing from this is a way to force a "publish" to either `preview` or `release`.  We need either a new management command for handling mass publishing or an option needs to be added to `reset_sync_states` to optionally merge to `preview` and / or `release` after running this command with the `--sync_backends` option.

**Comment by mbertrand** [comment]
One option is to flesh out the existing `trigger_pipelines`, which currently just starts new concourse pipeline builds (and optionally unpauses them), so that it also git merges to the appropriate draft/live branch, updates the appropriate website publish/preview status fields, etc.
