### ISSUE TITLE
new courses API returning images prefixed with /coursemedia

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#779]
### Steps to Reproduce

Visit the courses API filtered on courses with the starter `ocw-course` like: https://ocw-studio-rc.odl.mit.edu/api/websites/?type=ocw-course

### Expected Behavior

Course images (and other media) are prefixed with `/courses`

### Actual Behavior

Course images (and other media) are prefixed with `/coursemedia`

**Comment by pdpinch** [comment]
@gumaerc is this still an issue?

**Comment by gumaerc** [comment]
Closing this, as this was resolved by creating the `ocw-to-hugo` standalone Concourse pipeline which runs `ocw-to-hugo` with `--staticPrefix /courses`.  When this content was subsequently imported by `ocw-studio`, the URLs were updated.
