### ISSUE TITLE
Menu doesn't open for site collaborator page for certain users

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#803]
### Steps to Reproduce

I went to https://ocw-studio-rc.odl.mit.edu/sites/18-06-linear-algebra-spring-2010/collaborators/ and clicked on the three dots next to my name to show the context menu. No menu appears.

However if I add a fake user as a collaborator and then click to open the context menu, it shows up fine. Maybe there is a bug with handling of global admins?

**Comment by mbertrand** [comment]
The 3 dots probably shouldn't even appear next to global admins (and the site owner) - they cannot be deleted nor changed to editors.
