### ISSUE TITLE
Github backend sync doesn't handle renamed / moved files

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#807]
### Steps to Reproduce

 - Change the dirpath or filename of a `WebsiteContent` object
 - Publish the site in question

### Expected Behavior

The move / rename is reflected in the Github backend for the site

### Actual Behavior

The old file remains in the repo and a new file is created

**Comment by mbertrand** [comment]
It actually does handle renamed/moved files, I think what is missing here is committing the file to the main branch after you change the dirpath or filename.  Publishing does not commit anything to main, it merges whatever is currently in main to preview or publish branches.  If you change the the dirpath or filename, you need to get that commit into the main branch afterward, before publishing.

Did this happen after you ran `reset_sync_states` command, and without the `--sync_backends` option?  That command should probably be modified to have more filter options (like `--filter`, `--starter`, `--source`) and maybe the `--sync_backends` option should actually be mandatory).

**Comment by mbertrand** [comment]
```python
from content_sync.signals import *
from websites.models import *

website = Website.objects.get(name=<your_site_name>)
wc = WebsiteContent.objects.filter(website=website, type="page").order_by("-updated_on").first()
wc.dirpath="content/pagetest"
wc.save()

css = ContentSyncState.objects.get(content=wc)
css.synced_checksum = None
css.save()

backend = api.get_sync_backend(website)
backend.sync_all_content_to_backend()
```

Before:

<img width="563" alt="Screen Shot 2021-11-15 at 8 27 58 AM" src="https://user-images.githubusercontent.com/187676/141790260-9060dfe5-35f3-4fd2-9b21-d394b6a8a75c.png">

After:
<img width="550" alt="Screen Shot 2021-11-15 at 8 28 31 AM" src="https://user-images.githubusercontent.com/187676/141790273-b53e6d1e-5404-415f-ad8f-3f4202160d26.png">

**Comment by mbertrand** [comment]
I suspect that running ocw import locally against the RC git repos might also cause things to get out of sync - might be best to clear out those repos entirely and start from scratch, and avoid doing local ocw imports unless using a personal git organization.
