### ISSUE TITLE
Some imported OCW sites get invalid short_id values

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#827]
### Steps to Reproduce

Run `manage.py import_ocw_course_sites --bucket  ocw-to-hugo-output-qa --filter 18-443-statistics-for-applications --create_backend` to import the following sites:

18-443-statistics-for-applications-fall-2003
18-443-statistics-for-applications-fall-2006
18-443-statistics-for-applications-spring-2015 

### Expected Behavior
The sites are imported along and github repos created

### Actual Behavior

The github repos are not created, because the short_id values have parentheses:
`18.650-(formerly-18.443)-spring-2015`

**Comment by pdpinch** [comment]
Why are we favoring the old course number instead of the current one?

`18-443-statistics-for-applications-spring-2015`

> Actual Behavior
> The github repos are not created, because the short_id values have parentheses:
> 18.650-(formerly-18.443)-spring-2015
>

**Comment by mbertrand** [comment]
The `short_id` is derived from the json's `primary_course_number` field, which in this case is: `18.650 (formerly 18.443)`

The url/name `18-443-statistics-for-applications-spring-2015` is coming from json file's S3 filepath.  

https://ocw-studio-rc.odl.mit.edu/admin/websites/website/6c859e25-7833-441d-a47c-8572e4e7cc14/change/
