### ISSUE TITLE
Add  a new uid field to the metadata in ocw-studio

### ISSUE THREAD

**Issue by abeglova** [mitodl/ocw-studio#870]
In order to match legacy courses imported to ocw studio to the existing plone courses in ocw search we will need to import the course uid when we import courses.

We will save the course uid from Plone as the `legacy_uid` in the metadata. This uid should only be set for legacy courses. We will also export the uuid generated for the website in ocw-studio as the `site_uid`

**Comment by pdpinch** [comment]
@abeglova can we close this?
