### ISSUE TITLE
Display the file name in the resource metadata drawer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#878]
As a course author, I would like to know the filename a resource will use when it is published, particularly for documents. 

Currently [the resource drawer in studio ](https://ocw-studio-rc.odl.mit.edu/sites/peters-test-2021-09-29-1/type/resource/edit/be421ae9-9830-40f0-aab6-cb2847d262af/)displays the resource title, but not the filename:

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/430126/171850785-d347ae1e-48f7-4784-bcbf-345ff8b6903d.png">

#### Designs and Mockups

There's no mock-up, but we can just add a read-only field below Title. 

#### Acceptance Criteria:

- [ ] Display the filename in the resource drawer 

#### Out of scope

- It would be best for the filename to be a read-only field. I believe changing a filename would require syncing updates to S3.

**Comment by pdpinch** [comment]
I updated the description in an effort to make this clearer.

**Comment by pt2302** [comment]
Completed in https://github.com/mitodl/ocw-studio/pull/1406.
