### ISSUE TITLE
The last link in a table gets corrupted after save and load

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#903]
WIP bug description

### Steps to Reproduce

1. Create a site 
2. Create a resource, like a PDF
3. Create a page
4. Create a table on the page with three rows
5. In the first row, add a link to the PDF Resource. Repeat for each row
6. Save the page
7. Open the page

### Expected Behavior

- When the page is opened, it should look the same as it did when it was saved, e.g. 

### Actual Behavior

- When the page is opened, the code for the last link is visible, instead of displaying as a link. 

### Stacktrace

(Optional)

### Related Issues

(Optional)

### Screenshot or Screencast

(Optional)

**Comment by ChristopherChudzicki** [comment]
Fixed by #927
