### ISSUE TITLE
issue with resource link regex

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#917]
### Steps to Reproduce

1. create two resource links on a single line (i.e. within a single paragraph) in the Markdown editor
2. save the page
3. re-open the content editor, and note that the first resource link has gobbled up the second (see screens below)

### Expected Behavior

links shouldn't cannibalize each other

### Screenshot or Screencast

1. create a paragraph with two links:
<img width="838" alt="Screen Shot 2022-01-21 at 9 06 46 AM" src="https://user-images.githubusercontent.com/6207644/150540966-fb33a09e-354a-4011-990a-3f5d4294b884.png">

2. it saves as the markdown we expect:
<img width="889" alt="Screen Shot 2022-01-21 at 9 09 12 AM" src="https://user-images.githubusercontent.com/6207644/150541018-643ddccb-b7fb-4538-8e42-783d4cc36762.png">

```md
a thing {{< resource_link 9f27dc7b-2d7e-f67f-fac9-9260d4ae99dc \"is linked\" >}} and then so is {{< resource_link c46db57c-9699-3827-ec0c-6590087f8ace \"another thing\" >}} ok great

1. sdf
2. asdf
3. asdf
```

3. re-open the editor, and this will happen :/

<img width="832" alt="Screen Shot 2022-01-21 at 9 10 29 AM" src="https://user-images.githubusercontent.com/6207644/150541183-14857664-d378-4b0e-94d8-4bd23b08a802.png">

**Comment by pdpinch** [comment]
possibly the same issue as #903

**Comment by ChristopherChudzicki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chris Chudzicki](https://trello.com/c/W8h7BkWL/8756-chris-chudzicki)
