### ISSUE TITLE
Implement basic file upload

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#92]
[Wireframe](https://lucid.app/lucidchart/6be33dd8-f7db-47f8-8af8-338255f23c3c/edit?shared=true&page=gw.UNA5605io#?folder_id=home&browser=icon)

The goal of this issue is to enable file upload for resources in a way that ensures the file will be included in the generated static site.

In terms of UI, we will go with the simplest option to start out. We should be able to use a basic HTML input with type="file", and a simple text caption indicating the uploaded file if there is one. If there's an even simpler approach, we can go with that. A more UX-friendly file uploader can be worked on in a separate issue when the need arises.

**Acceptance criteria:**
- A site config field with type "file" should result in the file input being rendered in the relevant authoring UI
  - If a file has already been uploaded for the resource, the file name (with no path or uid) should be shown. Note that if we use the basic HTML input, we can't populate the value, so this can just be simple text underneath the input.
- When a file is uploaded and the resource record is saved, the file is saved to the configured Django storages backend 
  - To start out, we can namespace the files by site uuid and file type, and we should make sure to avoid name collisions. One way to do that would be to prefix each file with a separate uuid. Example: uploading `syllabus.pdf` --> file saved at `<storages destination>/<site uuid>/pdf/<uuid generated for file>_syllabus.pdf`.
- If a file was already uploaded for the particular resource, the newly-uploaded file should be saved and the old one deleted.
- If the file fails to upload, an error message should be shown under the input in the same way that a validation error would be shown.
- In the WebsiteContent record, the "file" value in the metadata should be set to the uploaded file path relative to the Storages root destination, or relative to the site folder within that storages destination (`<site uuid>/pdf/<file uuid>_syllabus.pdf` or `pdf/<file uuid>_syllabus.pdf` in the example above)
- S3 buckets and credentials created by devops, and credentials added to Vault
- Salt-ops PR(s) created and merged so that CI/RC/Prod are all ready to upload to the relevant buckets

**Not needed yet:**
- External URLs allowed instead of uploaded files

**Comment by mbertrand** [comment]
@shaidar for the S3 buckets, looks like [they were already created](https://github.com/mitodl/salt-ops/issues/1343) but do you know what their names are?  There is an `AWS_STORAGE_BUCKET_NAME` env variable for the app but no values for it yet on heroku.

**Comment by shaidar** [comment]
@mbertrand The bucket and creds should be all set on CI and RC

**Comment by mbertrand** [comment]
@gsidebo does it make sense to add `django-storages` as a requirement, set `OCW_STUDIO_USE_S3=True`, and add a nullable `FileField` to `WebsiteContent` (in addition to saving the relative filepath in the metadata)?  Or would you prefer that the file upload always ends up on S3 regardless of the `OCW_STUDIO_USE_S3` setting and not be saved to a `FileField`?

**Comment by gsidebo** [comment]
@mbertrand Definitely want `django-storages` as a dependency, but we should take care to make sure this works with any storage backend including the local fs. I can pretty confidently say that we don't want to make S3 storage a hard requirement for running the app. Obviously this gets a bit complicated if we're using local fs storage while running the app locally and we also have imported OCWS course sites with S3-based files. I thought about adding a FileField a while back. It would be a really great addition, not the least because we'd be able to set/remove files in Django admin. I'm not sure if we can make that work in that scenario where we use local fs storage for new files while also handling the S3-based files from imported course sites. Do you want to dig into that and see what's possible?

**Comment by mbertrand** [comment]
It's possible to save a file value for an imported course resource to be equal to the "file_location" in the metadata, for example:
```
wc.metadata["file_location"]
> '/coursemedia/sts-005-disease-and-society-in-america-fall-2005/c364a095ae63b71b4b8f8ab6ce75ac27_study_guide_6.pdf'

wc.file = wc.metadata["file_location"]
wc.save()
```

However, the full file url then becomes `https://<AWS_STORAGE_BUCKET_NAME>.s3.amazonaws.com/coursemedia/...study_guide_6.pdf` which currently is not the same bucket that the file is actually in.  

Not sure if the plan is to copy existing files from the current ocw-www bucket to the ocw-studio bucket, or to use the same bucket for both ocw-www and ocw-studio?  It seems that the bucket used by the ocw-www site is the one that files should be uploaded to anyway, so maybe they should be the same.

**Comment by gsidebo** [comment]
@mbertrand Yeah, whatever our `AWS_STORAGE_BUCKET_NAME` is, that would need to have the relevant files, whether we decide to point it at the ocw-www buckets or move/copy the files in those buckets to ocw-studio. Are you looking into the possibility of local-fs-based files and S3-based files coexisting? Might involve some custom storage class that uses both the S3 and local fs classes. Maybe an added model field to indicate the backend? If we can't make something like that work, then I feel like we should (a) treat OCW-imported files as a special case and leave the FileField null for those, or (b) drop the idea for the FileField.

**Comment by mbertrand** [comment]
I'm not really clear what the use case is for saving some files on S3 and some on the local FS.  I'm assuming CI, RC, and production will always be saving to S3, and our dev instances will usually not except when we want to specifically test that uploading to S3 actually works - is that incorrect?  In terms of saving files locally for dev work, I think the worst that would happen is that the imported OCW courses wouldn't have viewable files?  

Saving to file or S3 can be controlled with the env variable `OCW_STUDIO_USE_S3`.  However, if you have `OCW_STUDIO_USE_S3=False`, upload files and save them locally, then switch to `OCW_STUDIO_USE_S3=True`, the files saved locally will be presumed to actually be on S3.  So in. terms of dev work I think the worst that would happen is that the files wouldn't be viewable if they were saved to the local FS and then S3 is enabled, or vice versa.

**Comment by gsidebo** [comment]
I was thinking about cases where we would want to edit existing content or build the site from a locally-running app. If the app is using local storage and imported OCW course site files remain on S3, you wouldn't be able to do either. I guess we're a long way from being able to edit/build imported OCW sites in Studio, so I guess we can just punt on this for now. Something to keep in mind, though. For now, I agree w/ the plan to add a FileField 👍

**Comment by mbertrand** [comment]
@sar what do you think of ocw-next and ocw-studio pointing to the same S3 bucket in each environment, is that doable?  Or is it already configured that way and I just don't know it?

**Comment by mbertrand** [comment]
It's possible to have multiple file fields pointing to different storage backends, though that seems a bit cumbersome. Example:
```python
    file_1 = models.FileField() # Uses default storage
    file_2 = models.FileField(storage=S3BotoStorage(bucket='other-bucket'))
```
But then the code has to account for that and know which field to save/retrieve from under specified conditions.

**Comment by mbertrand** [comment]
So we could have a `local_file` and an `s3_file` field, and perhaps an `is_local` boolean field, for `WebsiteContent`.  `is_local` would be set to the opposite of whatever the value of `OCW_STUDIO_USE_S3` is at the time.  If `False`, uploaded files get saved to `local_file` and `is_local` is set to `True`.  Otherwise, uploaded files get saved to `s3_file` and `is_local` is set to `False`.  When needing to view/retrieve the file, `is_local` determines which field to read.

**Comment by gsidebo** [comment]
Yeah I think we should avoid having multiple file fields. I'd prefer writing some kind of import script that brings down all the S3 files to the local fs over that. Could be run as needed for individual sites when developing locally. I think we can forge ahead with a single file field and a single storage backend

**Comment by shaidar** [comment]
@mbertrand Right now ocw-next is using those [two buckets](https://github.com/mitodl/salt-ops/blob/main/pillar/apps/ocw-next-production.sls#L3-L4) and ocw-studio is using [this bucket](https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/ocw-studio.sls#L53). I could be wrong, but I would think that maintaining that separation is a good thing to at least keep content uploaded through ocw-studio separate from content imported from legacy OCW or we don't really care about that and/or we can obtain that metadata elsewhere?

**Comment by mbertrand** [comment]
Files uploaded to ocw-studio will eventually have to be served from ocw-next once the course is published, and files already on ocw-next need to be available in ocw-studio to view.  I can think of a couple options that allow for separate project buckets:

a) When a course is published in ocw-studio, copy all its files from the ocw-studio bucket to the ocw-next bucket.  For course files already on ocw-next, modify the existing `backpopulate_ocw_course_sites` management command (or create a new one) to copy all the files from the ocw-next bucket to the ocw-studio bucket.  The disadvantage of this though is that published sites will have the same files in 2 buckets, leading to extra storage costs.

b) Set up ocw-next's cloudfront instance to serve files from both buckets (ditto for ocw-studio). In this case the root path of file urls for any new sites would need to be different than those for the legacy sites:
   Legacy site example: ../**coursemedia**/<site_slug>/<resource_slug>_MIT17_S916IAP20_Example1.pdf
   Studio site example: ../**course_media**/<site_slug>/<resource_slug>_MIT17_S916IAP20_Example1.pdf
   
This option still leaves the problem of viewing files for the legacy site files in ocw-studio.  @gsidebo in the OCW Authoring doc you mentioned the possibility of allowing users to enter an external URL for any file resource instead of uploading it.  This would likely entail a separate model field (`external_url`) that we could use to store the cloudfront links to the legacy site files.    But if a user decides to change a few things on a legacy site in ocw-studio and publish, should all its file paths be updated or just any new ones that were uploaded?

**Comment by mbertrand** [comment]
Now that I think more about it, option a above is likely much better because it allows for changing a file in ocw-studio without affecting the current file served from ocw-next until the change is published.

**Comment by mbertrand** [comment]
Another thing to consider: what if someone decides to modify an existing resource, uploads a new file, then changes their mind and wants to revert to the old file before publishing (and they didn't think to download the old file locally beforehand)?  Punt on that and handle in a future PR or deal with it now?

**Comment by pdpinch** [comment]
I don’t think file versioning is worth our time now. 

We do typically have versioning turned on in S3, so if any CMS user has a major regret, we can work it out. 

> Another thing to consider: what if someone decides to modify an existing resource, uploads a new file, then changes their mind and wants to revert to the old file before publishing (and they didn't think to download the old file locally beforehand)?

**Comment by mbertrand** [comment]
>Example: uploading syllabus.pdf --> file saved at `<storages destination>/<site uuid>/pdf/<uuid generated for file>_syllabus.pdf`

@gsidebo the current filepath pattern for existing OCW content is `<site_name>/<uuid generated for file>_syllabus.pdf` ([example](https://ocwnext-rc.odl.mit.edu/coursemedia/5-61-physical-chemistry-fall-2017/a4e1b8a33bf1bb3b75dd2ecb257dc397_MIT5_61F17_final_sol.pdf)) - okay to keep it that way?

**Comment by gsidebo** [comment]
@mbertrand Yeah since `Website.name` is unique that sounds great. Namespacing by file type probably isn't necessary
