### ISSUE TITLE
add a draft setting on pages, resources, etc to hide them on the published site 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#933]
As a course author, sometimes I create a page (or a resource, or a video gallery, etc.) and then decide I don't want to publish it in the course -- at least not right now. I'd like a way to mark pages, etc as "draft" or do not "publish" 

In particular, I need to hide / remove the "Beta Notification" banner from the home page on https://ocw-published.odl.mit.edu/

@alicewriteswrongs said:
> hugo has [support for draft and future content](https://gohugo.io/getting-started/usage/#draft-future-and-expired-content) so we could certainly leverage that.

#### Acceptance Criteria:

- [ ] Add a "draft" setting to all the collection types in the studio yml 
- [ ] "draft" should default to false
- [ ] if "draft" is checked, then the page/resource/whatever should not be part of the published site HTML

**Comment by alicewriteswrongs** [comment]
hugo has [support for draft and future content](https://gohugo.io/getting-started/usage/#draft-future-and-expired-content) so we could certainly leverage that.

I think we could actually add support for this just by changing the content configuration to add a boolean field called `draft`
