### ISSUE TITLE
Google drive sync from ocw-www starter course fails

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#943]
### Steps to Reproduce
1. Create new course from ocw-www starter
2. Navigate to resources and add some resources to google drive "Files Final" folder
3. Click Sync

### Expected Behavior
Sync succeeds

### Actual Behavior
Sync fails

### Stacktrace
```
ocw-studio-celery-1  | [2022-01-28 18:44:52,210: ERROR/ForkPoolWorker-4] Error creating resource for drive file 14jXIzIarBliASFemkM-vZ7UMaNRibP7K
ocw-studio-celery-1  | Traceback (most recent call last):
ocw-studio-celery-1  |   File "/src/gdrive_sync/api.py", line 372, in create_gdrive_resource_content
ocw-studio-celery-1  |     **SiteConfig(
ocw-studio-celery-1  |   File "/src/websites/site_config_api.py", line 146, in generate_item_metadata
ocw-studio-celery-1  |     if (
ocw-studio-celery-1  | KeyError: 'metadata'
```

_Happens on local and _RC__

**Comment by ChristopherChudzicki** [comment]
@pdpinch **Question:** Should sites created from the ocw-www starter have a resources tab?

**Comment by pdpinch** [comment]
Yes, at least from a product perspective. We would like to be able to add images to the ocw-www site in the future. 

This isn’t urgent though.

**Comment by alicewriteswrongs** [comment]
One related thing we've talked about a few times but haven't cemented is making it so that all sites have a resource content type by default, which would imply that the configuration for that content type does not live with the site configuration (through yaml) but is hardcoded in the ocw-studio codebase
