### ISSUE TITLE
Backpopulate Learning Resource Types

### ISSUE THREAD

**Issue by abeglova** [mitodl/ocw-studio#948]
Once a course is imported into studio, the `Learning Resource Types` field becomes the source of truth for the `Resource Type` in the resource field sidebar. These values are currently not populated when ocw courses are imported into studio and are blank for imported courses. To have the `Resource Type` filter work when after we run the new resource index task, we need to write run a script to backpopulate those values for imported courses and update the course importer to set `Learning Resource Types`.

**Comment by Ferdi** [comment]
Is this field directly populated in search index only ?

**Comment by abeglova** [comment]
For old OCW courses we have a hacky way to populate it in the index only based on the title of the "section" page of the resource (which is saved in the database for the ContentFile). We find the section by looking for the parent resource of the resource, then the parent's parent then so on until we find a page who's parent is the course home page

**Comment by abeglova** [comment]
For new ocw courses we don't currently save the parent in the data.json file for the resource. We do save the parent in ocw-studio WebsiteContent objects so it would be pretty straight forward to populate the Resource Types in ocw-studio based on the existing mapping from open-discussions

**Comment by abeglova** [comment]
Unfortunately it looks like I need the page type and parent type fields to get the “Section” page. In order to get the data we need to get the resource types I made a pr to add type, parent_type and parent_title to the pages and resources generated by ocw-to-hugo

**Comment by pdpinch** [comment]
@abeglova can this be closed?
