### ISSUE TITLE
Multiple routes on cw-preview.odl.mit.edu return 301

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#959]
### Steps to Reproduce

For example:

1. Visit ocw-studio.odl.mit.edu and click into a site, e.g. https://ocw-studio.odl.mit.edu/sites/ocw-www/
2. Open the publish drawer and click the link to the preview site,  https://ocw-preview.odl.mit.edu/
3. The home page loads, but many links from the home page fail, for example
    - https://ocw-preview.odl.mit.edu/search
    - all courses, for example: https://ocw-preview.odl.mit.edu/courses/18-100b-analysis-i-fall-2010
    - https://ocw-preview.odl.mit.edu/about

### Expected Behavior

- If the sites are published, the links should work

### Actual Behavior

- 301 errors 

### Screenshot or Screencast

<img width="589" alt="image" src="https://user-images.githubusercontent.com/430126/152209967-46adf35b-0077-431d-9e9d-34f22526cc6e.png">

**Comment by pdpinch** [comment]
I tried clearing the fastlly cache for https://ocw-preview.odl.mit.edu/search, but I got an error from the fastly admin site

**Comment by pdpinch** [comment]
> mattbert  4 minutes ago
> The links seem to work if you add / to the end of them

**Comment by blarghmatey** [comment]
This is resolved now. There was a missing VCL snippet that did the processing of redirect responses that is in place now.
