### ISSUE TITLE
/sites Course search loses focus + cursor position as typing

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#963]
### Steps to Reproduce
1. Use the search bar in upper right to search for a site https://ocw-studio-rc.odl.mit.edu/sites
2. Type in a phrase, but type kinda slowly

### Expected Behavior
Search input should maintain focus + cursor position so user can continue typing

### Actual Behavior
Search input loses focus, so if you want to keep typing you have to click on it again.

### Screenshot or Screencast

<details open>
<summary> Open/close gif </summary>

![course_search_reloads_studio](https://user-images.githubusercontent.com/9010790/152370457-05016d3b-445a-4a89-a7f1-ddc070c0101b.gif)

</details>

**Comment by alicewriteswrongs** [comment]
it's a pretty hacky search right now, so iirc there is a debounced thing that leads to a full page refresh. We should definitely update it to something more robust at some point
