### ISSUE TITLE
multiple repos for course `res-15-005-healthcare-finance-15-482x-spring-2019`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#979]
1. For some reason, studio creates a new repo for `res-15-005-healthcare-finance-15-482x-spring-2019` every time it is imported
2. The course does not publish either

### Expected Behavior

Should be a very simple course, based on https://ocw.mit.edu/resources/res-15-005-healthcare-finance-15-482x-spring-2019/ 

### Actual Behavior

- multiple repos: https://github.mit.edu/ocw-content-rc?q=res.15-005-spring-2019&type=
- failed publish, due to missing description: https://cicd-qa.odl.mit.edu/teams/ocw/pipelines/draft/jobs/build-ocw-site/builds/49?vars.site=%22res-15-005-healthcare-finance-15-482x-spring-2019%22#L62018b43:11

**Comment by pdpinch** [comment]
The correct repo looks to be this one: https://github.mit.edu/ocw-content-rc/res.15-005-spring-2019

**Comment by mbertrand** [comment]
The repo [res.15-005-spring-2019](https://github.mit.edu/ocw-content-rc/res.15-005-spring-2019) is for [res-15-005-healthcare-finance-spring-2019](https://ocw-draft-qa.global.ssl.fastly.net/courses/res-15-005-healthcare-finance-spring-2019/), the repo [res.15-005-spring-2019-28](https://github.mit.edu/ocw-content-rc/res.15-005-spring-2019-28) is for [res-15-005-healthcare-finance-15-482x-spring-2019](https://ocw-draft-qa.global.ssl.fastly.net/courses/res-15-005-healthcare-finance-15-482x-spring-2019/).  There seems to be a fault in the logic used to determine what the repo should be when there are multiple sites that match the base name, causing one of the sites to get a new repo every time it is imported.
