### ISSUE TITLE
search on `/sites` needs to match on more fields

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/ocw-studio#990]
### Steps to Reproduce

Search for a course number

### Expected Behavior

the associated course should pop up

### Actual Behavior

it most certainly does not!

### what's going on

Right now the search field on `/sites` _only_ matches on the `title` field on the website model. This means that for a lot of courses things that course authors might think they can search for (like the course number, or a fragment of the `name` field) actually will not match at all.

We should improve this by searching on `title`, `name`, and `short_id`.

**Comment by pdpinch** [comment]
Also, course number, for example `8.701`

**Comment by alicewriteswrongs** [comment]
yes, course number is found in the `short_id` field
