### ISSUE TITLE
Prompt user to save work when opening the publish drawer 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#991]
As a course author, I don't want to lose my work when I open the publish drawer and publish the course. 

We have a warning when the course author navigates away from the page without saving, but we don't have one when the course author opens the publish drawer, which can also be destructive. 

### To Do _updated by chris_
**Overall issue:** We don't want people to lose edits **and** we want to warn them when publishing with unsaved frontend edits (dirty forms).

**Steps to address:**
- [x] 1. If somehow "Publish" is initiated with a dirty form, data in the dirty form should not be lost.
- [x] 2. Warn user (prompt for confirmation) when navigating would lose information. E.g., navigating from "Metadata" to "Pages" after editing metadata without saving. 
- [x] 3. Clicking "Publish" with dirty forms (unsaved frontend edits) should warn user somehow. 

    *I lean toward an alert badge inside the publish drawer. I.e., still let people open the drawer. The drawer has useful info like links to ocw / staging*

**Comment by ChristopherChudzicki** [comment]
@dseaton or @pdpinch Interested in your thoughts on below....*tldr: I think opening the publish drawer should NOT be destructive. There are a few other related usability issues we should fix.*

First...I want to make sure I understand the behavior in question. 

Currently, when a user does some actions such as
- edit metadata
- rearrange menus
then clicks "Publish --> Publish", the page content seems to reload and so any unsaved work is lost. 

I think that there are really three issues here:
1. Clicking publish causes page content to re-render, losing unsaved progress.

    **Resolution:** Don't re-render the page content when clicking publish. It's unnecessary. _And it should not happen. It only happens because of a quirk in how one of our components is constructed._
2. Making edits to "metadata", "menus", etc and navigating away without saving does NOT currently warn user. (As far as I can tell, only unsaved changes in the editing drawer warn user).

    **Resolution:** Warn using when navigating would lose unsaved changes.
3. Clicking "Publish" does not warn user that  they have unsaved changes.

    **Resolution:** Warn user "You have unsaved changes" before publishing.


(1) and (2) are very easy to do.

I suspect that (3) is a bit trickier, though I haven't looked into it too much. The difficulty with (3) is that the editing forms in studio all have deliberately local state, which makes it hard for the "Publish" button to be aware of their state. _But fixing (1) and (2) would be a big step... At worst, someone hits "Publish", publishes with unsaved changes, then tries to navigate, and realizes they have unsaved changes, and has to save and re-publish._

**Comment by dseaton** [comment]
This sounds very reasonable to me.

**Comment by pdpinch** [comment]
Let's do the easy stuff first and see if that addresses the issue.
