### ISSUE TITLE
Missing instructor on ocw-studio-prod

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-studio#999]
### Steps to Reproduce

Go to the 22.01-fall-2021 site on [ocw-studio-prod](https://ocw-studio.odl.mit.edu/sites/introduction-to-nuclear-engineering-and-ionizing-radiation/type/metadata/) and try to add "Prof. Michael Short" as an instructor. Mike appears in the search results on [ocw-studio-rc](https://ocw-studio-rc.odl.mit.edu/sites/22-01-introduction-to-nuclear-engineering-and-ionizing-radiation-fall-2016/type/metadata/) and can be added, but not on prod.

### Expected Behavior

"Prof. Michael Short" should appear in the list of Instructor on ocw-studio-prod.

### Actual Behavior

"Prof. Michael Short" does not appear in the list of Instructor on ocw-studio-prod.

### Screenshot or Screencast

ocw-studio-prod, no option for Prof. Michael Short
![image](https://user-images.githubusercontent.com/1703442/153667337-e64230a0-e9e1-470b-98de-04552d21cf11.png)

ocw-studio-rc, Prof Michael Short added as an instructor. 
![image](https://user-images.githubusercontent.com/1703442/153667668-f0c9ad1b-b1b2-49e9-97c5-b41fb0bdce47.png)

**Comment by pdpinch** [comment]
Of note, this instructor is in the ocw-www repo, at https://github.mit.edu/mitocwcontent/ocw-www/blob/main/content/instructors/d9ca5631-c693-6252-866d-63683c0c453e.md and he's getting published to https://ocwnext.odl.mit.edu/instructors/d9ca5631-c693-6252-866d-63683c0c453e/index.json

**Comment by dseaton** [comment]
At some point in the last two days, Prof. Mike Short appeared in the list of instructors on ocw-studio-prod. I am assuming a fix somewhere else in the codebase remedied this issue. Closing.
